import pymysql

products = [
    ('boAt Airdopes 441', 'boAt', 'Earbuds', 30),
    ('boAt Rockerz 550', 'boAt', 'Headphones', 25),
    ('boAt Stone 200', 'boAt', 'Speakers', 20),
    ('boAt Rockerz 255', 'boAt', 'Headphones', 15),
    ('boAt Stone 170', 'boAt', 'Speakers', 10),
    ('boAt Bassheads 100', 'boAt', 'Earbuds', 5),
    ('boAt Airdopes 131', 'boAt', 'Earbuds', 25),
    ('boAt Rockerz 450', 'boAt', 'Headphones', 20),
    ('boAt Stone 260', 'boAt', 'Speakers', 15),
    ('boAt Rockerz 255 Pro+', 'boAt', 'Headphones', 10),
    ('boAt Stone 1200', 'boAt', 'Speakers', 5),
    ('boAt Airdopes 402', 'boAt', 'Earbuds', 20),
    ('boAt Rockerz 510', 'boAt', 'Headphones', 15),
    ('boAt Stone 1000', 'boAt', 'Speakers', 10),
    ('boAt Rockerz 600', 'boAt', 'Headphones', 5),
    ('boAt Airdopes 131v2', 'boAt', 'Earbuds', 20),
    ('boAt Rockerz 400', 'boAt', 'Headphones', 15),
    ('boAt Stone 650', 'boAt', 'Speakers', 10),
    ('boAt Rockerz 255F Pro', 'boAt', 'Headphones', 5),
    ('boAt Airdopes 621', 'boAt', 'Earbuds', 20),
    ('boAt Airdopes 621B', 'boAt', 'Earbuds', 25),
    ('boAt Rockerz 255 Pro', 'boAt', 'Headphones', 20),
    ('boAt Stone 200A', 'boAt', 'Speakers', 15),
    ('boAt Airdopes 441 Pro', 'boAt', 'Earbuds', 10),
    ('boAt Rockerz 330', 'boAt', 'Headphones', 5),
    ('JBL Flip 5', 'JBL', 'Speakers', 20),
    ('JBL Quantum 800', 'JBL', 'Headphones', 12),
    ('JBL Charge 5', 'JBL', 'Speakers', 9),
    ('JBL Quantum 800', 'JBL', 'Headphones', 12),
    ('JBL Flip 5', 'JBL', 'Speakers', 20),
    ('JBL Quantum 800', 'JBL', 'Headphones', 12),
    ('JBL Charge 5', 'JBL', 'Speakers', 9),
    ('JBL Quantum 800', 'JBL', 'Headphones', 12),
    ('JBL Flip 5', 'JBL', 'Speakers', 20),
    ('JBL Quantum 800', 'JBL', 'Headphones', 12),
    ('JBL Charge 5', 'JBL', 'Speakers', 9),
    ('JBL Quantum 800', 'JBL', 'Headphones', 12),
    ('JBL Flip 5', 'JBL', 'Speakers', 20),
    ('JBL Quantum 800', 'JBL', 'Headphones', 12),
    ('JBL Charge 5', 'JBL', 'Speakers', 9),
    ('JBL Quantum 800', 'JBL', 'Headphones', 12),
    ('JBL Flip 5', 'JBL', 'Speakers', 20),
    ('JBL Quantum 800', 'JBL', 'Headphones', 12),
    ('JBL Charge 5', 'JBL', 'Speakers', 9),
    ('JBL Quantum 800', 'JBL', 'Headphones', 12),
    ('JBL Flip 5', 'JBL', 'Speakers', 20),
    ('JBL Quantum 800', 'JBL', 'Headphones', 12),
    ('JBL Charge 5', 'JBL', 'Speakers', 9),
    ('JBL Quantum 800', 'JBL', 'Headphones', 12),
    ('JBL Flip 5', 'JBL', 'Speakers', 20),
    ('OnePlus Bullets Wireless Z', 'OnePlus', 'Neckband', 30),
    ('OnePlus Buds Z', 'OnePlus', 'Earphones', 25),
    ('OnePlus Bullets Wireless Z Bass Edition', 'OnePlus', 'Neckband', 20),
    ('OnePlus Buds', 'OnePlus', 'Earphones', 15),
    ('OnePlus Bullets Wireless', 'OnePlus', 'Neckband', 10),
    ('OnePlus Bullets Wireless Z2', 'OnePlus', 'Neckband', 5),
    ('OnePlus Buds Pro', 'OnePlus', 'Earphones', 25),
    ('OnePlus Buds Z2', 'OnePlus', 'Earphones', 20),
    ('OnePlus Buds Pro White', 'OnePlus', 'Earphones', 15),
    ('OnePlus Buds White', 'OnePlus', 'Earphones', 10),
    ('OnePlus Buds Pro Black', 'OnePlus', 'Earphones', 5),
    ('OnePlus Bullets Wireless Z Blue', 'OnePlus', 'Neckband', 20),
    ('OnePlus Bullets Wireless Z Black', 'OnePlus', 'Neckband', 15),
    ('OnePlus Bullets Wireless Z Bass Edition Black', 'OnePlus', 'Neckband', 10),
    ('OnePlus Bullets Wireless Z Bass Edition White', 'OnePlus', 'Neckband', 5),
    ('OnePlus Buds Z Black', 'OnePlus', 'Earphones', 20),
    ('OnePlus Buds Z White', 'OnePlus', 'Earphones', 15),
    ('OnePlus Buds Gray', 'OnePlus', 'Earphones', 10),
    ('OnePlus Buds Z2 Black', 'OnePlus', 'Earphones', 5),
    ('OnePlus Buds Z2 White', 'OnePlus', 'Earphones', 20),
    ('OnePlus Buds Pro Blue', 'OnePlus', 'Earphones', 15),
    ('OnePlus Buds Pro Black', 'OnePlus', 'Earphones', 10),
    ('OnePlus Buds Pro Glossy White', 'OnePlus', 'Earphones', 5),
    ('OnePlus Buds Pro Matte Black', 'OnePlus', 'Earphones', 20),
    ('OnePlus Buds Pro Matte White', 'OnePlus', 'Earphones', 15),
    ('Noise Tune Charge', 'Noise', 'Neckband', 30),
    ('Noise Tune Elite', 'Noise', 'Neckband', 25),
    ('Noise Tune Flex', 'Noise', 'Neckband', 20),
    ('Noise Tune Active', 'Noise', 'Neckband', 15),
    ('Noise Tune Sport 2', 'Noise', 'Neckband', 10),
    ('Noise Tune Sport Pro', 'Noise', 'Neckband', 5),
    ('Noise Shots X5 Pro', 'Noise', 'Earphones', 25),
    ('Noise Shots Rush', 'Noise', 'Earphones', 20),
    ('Noise Shots X1 AIR', 'Noise', 'Earphones', 15),
    ('Noise Shots XO', 'Noise', 'Earphones', 10),
    ('Noise Shots X3 BASS', 'Noise', 'Earphones', 5),
    ('Noise Air Buds Pro', 'Noise', 'Earphones', 25),
    ('Noise Air Buds Mini', 'Noise', 'Earphones', 20),
    ('Noise Air Buds', 'Noise', 'Earphones', 15),
    ('Noise Buds Play', 'Noise', 'Earphones', 10),
    ('Noise Buds Solo', 'Noise', 'Earphones', 5),
    ('Noise Flair 2.0', 'Noise', 'Headphones', 20),
    ('Noise Defy Plus', 'Noise', 'Headphones', 15),
    ('Noise Defy', 'Noise', 'Headphones', 10),
    ('Noise Tune LITE', 'Noise', 'Headphones', 5),
    ('Noise Barrel 2.0', 'Noise', 'Speakers', 20),
    ('Noise Vibe 2.0', 'Noise', 'Speakers', 15),
    ('Noise Aqua 2.0', 'Noise', 'Speakers', 10),
    ('Noise Buddy 2.0', 'Noise', 'Speakers', 5),
    ('Realme Buds Wireless 2', 'Realme', 'Neckband', 30),
    ('Realme Buds Wireless 2 Neo', 'Realme', 'Neckband', 25),
    ('Realme Buds Wireless', 'Realme', 'Neckband', 20),
    ('Realme Buds Air 2', 'Realme', 'Earphones', 15),
    ('Realme Buds Air Pro', 'Realme', 'Earphones', 10),
    ('Realme Buds Air Neo', 'Realme', 'Earphones', 5),
    ('Realme Buds Q2', 'Realme', 'Earphones', 25),
    ('Realme Buds Q', 'Realme', 'Earphones', 20),
    ('Realme Buds Classic', 'Realme', 'Earphones', 15),
    ('Realme Buds Wireless Pro', 'Realme', 'Earphones', 10),
    ('Realme Buds 2', 'Realme', 'Earphones', 5),
    ('Realme Buds Air 3', 'Realme', 'Earphones', 25),
    ('Realme Buds Air 2 Neo', 'Realme', 'Earphones', 20),
    ('Realme Buds Air', 'Realme', 'Earphones', 15),
    ('Realme Buds Air 2 Pro', 'Realme', 'Earphones', 10),
    ('Realme Buds Air Pro Master Edition', 'Realme', 'Earphones', 5),
    ('Realme Buds Wireless 3', 'Realme', 'Earphones', 25),
    ('Realme Buds Wireless 2 Pro', 'Realme', 'Earphones', 20),
    ('Realme Buds Q2 Neo', 'Realme', 'Earphones', 15),
    ('Realme Buds Wireless Pro Master Edition', 'Realme', 'Earphones', 10),
    ('Realme Buds Wireless 2 Pro Master Edition', 'Realme', 'Earphones', 5),
    ('Realme Buds Air Pro 2', 'Realme', 'Earphones', 25),
    ('Realme Buds Air 2 Neo Active', 'Realme', 'Earphones', 20),
    ('Realme Buds Air 2 Neo Bass Boost+', 'Realme', 'Earphones', 15),
    ('Realme Buds Air 2 Neo Bass Boost', 'Realme', 'Earphones', 10),
    ('Realme Buds Air 2 Neo Bass', 'Realme', 'Earphones', 5),
    ('Redmi SonicBass Wireless Earphones', 'Redmi', 'Earphones', 30),
    ('Redmi Earbuds 2C', 'Redmi', 'Earphones', 25),
    ('Redmi Earbuds S', 'Redmi', 'Earphones', 20),
    ('Redmi Hi-Resolution Audio Wired Earphones', 'Redmi', 'Earphones', 15),
    ('Redmi Earbuds 3 Pro', 'Redmi', 'Earphones', 10),
    ('Redmi Earbuds 3', 'Redmi', 'Earphones', 5),
    ('Redmi SonicBass Wireless Neckband Earphones', 'Redmi', 'Neckband', 25),
    ('Redmi Neckband Wireless Earphones', 'Redmi', 'Neckband', 20),
    ('Redmi Earbuds 3 TWS', 'Redmi', 'Earphones', 15),
    ('Redmi Earbuds 2C TWS', 'Redmi', 'Earphones', 10),
    ('Redmi Earbuds 2 TWS', 'Redmi', 'Earphones', 5),
    ('Redmi SonicBass Wireless Earphones 2', 'Redmi', 'Earphones', 30),
    ('Redmi Earbuds 3 Pro TWS', 'Redmi', 'Earphones', 25),
    ('Redmi Earbuds 3 TWS Pro', 'Redmi', 'Earphones', 20),
    ('Redmi Earbuds 3 Pro Max', 'Redmi', 'Earphones', 15),
    ('Redmi AirDots 3 Pro', 'Redmi', 'Earphones', 10),
    ('Redmi AirDots 3', 'Redmi', 'Earphones', 5),
    ('Redmi SonicBass Wireless Neckband Earphones 2', 'Redmi', 'Neckband', 25),
    ('Redmi Earbuds 3 Pro TWS Lite', 'Redmi', 'Earphones', 20),
    ('Redmi Earbuds 3 TWS Lite', 'Redmi', 'Earphones', 15),
    ('Redmi Earbuds 2C TWS Lite', 'Redmi', 'Earphones', 10),
    ('Redmi SonicBass Wireless Earphones 2 Pro', 'Redmi', 'Earphones', 5),
    ('Redmi AirDots 3 Pro Max', 'Redmi', 'Earphones', 30),
    ('Redmi Earbuds 3 Pro TWS Max', 'Redmi', 'Earphones', 25),
    ('Redmi Earbuds 3 TWS Pro Max', 'Redmi', 'Earphones', 20),
    ('Apple AirPods Max', 'Apple', 'Headphones', 30),
    ('Apple AirPods Pro', 'Apple', 'Earphones', 25),
    ('Apple AirPods (3rd generation)', 'Apple', 'Earphones', 20),
    ('Beats Studio Buds', 'Apple', 'Earphones', 15),
    ('Beats Flex', 'Apple', 'Earphones', 10),
    ('Beats Powerbeats Pro', 'Apple', 'Earphones', 5),
    ('Beats Solo Pro', 'Apple', 'Headphones', 25),
    ('Beats Solo3 Wireless', 'Apple', 'Headphones', 20),
    ('Beats EP', 'Apple', 'Headphones', 15),
    ('Beats Studio3 Wireless', 'Apple', 'Headphones', 10),
    ('Beats Pill+', 'Apple', 'Speakers', 25),
    ('Beats Pill XL', 'Apple', 'Speakers', 24),
    ('Beats Pill 2.0', 'Apple', 'Speakers', 23),
    ('Beats Pill Mini', 'Apple', 'Speakers', 21),
    ('Beats Pill Dude', 'Apple', 'Speakers', 20),
    ('Beats Pill Character', 'Apple', 'Speakers', 19),
    ('Beats Pill Sleeve', 'Apple', 'Speakers', 18),
    ('Beats Pill+ App', 'Apple', 'Speakers', 17),
    ('Beats Pill+ Stand', 'Apple', 'Speakers', 16),
    ('Beats Pill XL+', 'Apple', 'Speakers', 12),
    ('OnePlus Watch', 'OnePlus', 'Smartwatches', 30),
    ('OnePlus Watch Cobalt Limited Edition', 'OnePlus', 'Smartwatches', 25),
    ('OnePlus Watch Harry Potter Edition', 'OnePlus', 'Smartwatches', 20),
    ('OnePlus Watch Cyberpunk 2077 Edition', 'OnePlus', 'Smartwatches', 15),
    ('OnePlus Watch LX', 'OnePlus', 'Smartwatches', 10),
    ('OnePlus Watch Cobalt Limited Edition RWBY', 'OnePlus', 'Smartwatches', 5),
    ('Noise ColorFit Ultra', 'Noise', 'Smartwatches', 30),
    ('Noise ColorFit Pro 3', 'Noise', 'Smartwatches', 25),
    ('Noise ColorFit Pro 2', 'Noise', 'Smartwatches', 20),
    ('Noise ColorFit Pro', 'Noise', 'Smartwatches', 15),
    ('Noise ColorFit Nav', 'Noise', 'Smartwatches', 10),
    ('Noise ColorFit Pulse', 'Noise', 'Smartwatches', 5),
    ('boAt Xtend', 'boAt', 'Smartwatches', 30),
    ('boAt Watch Enigma', 'boAt', 'Smartwatches', 25),
    ('boAt Flash', 'boAt', 'Smartwatches', 20),
    ('boAt Xplorer', 'boAt', 'Smartwatches', 15),
    ('boAt Flash Pro', 'boAt', 'Smartwatches', 10),
    ('boAt Watch Storm', 'boAt', 'Smartwatches', 5),
    ('Apple Watch Series 7', 'Apple', 'Smartwatches', 30),
    ('Apple Watch SE', 'Apple', 'Smartwatches', 25),
    ('Apple Watch Series 6', 'Apple', 'Smartwatches', 20),
    ('Apple Watch Series 5', 'Apple', 'Smartwatches', 15),
    ('Apple Watch Series 4', 'Apple', 'Smartwatches', 10),
    ('Apple Watch Series 3', 'Apple', 'Smartwatches', 5),
    ('Fire-Boltt 360', 'Fire-Boltt', 'Smartwatches', 30),
    ('Fire-Boltt Ninja', 'Fire-Boltt', 'Smartwatches', 25),
    ('Fire-Boltt Beast', 'Fire-Boltt', 'Smartwatches', 20),
    ('Fire-Boltt Thunder', 'Fire-Boltt', 'Smartwatches', 15),
    ('Fire-Boltt Ring', 'Fire-Boltt', 'Smartwatches', 10),
    ('Fire-Boltt Fuel', 'Fire-Boltt', 'Smartwatches', 5),
    ('iPhone 13', 'Apple', 'Mobile Phones', 50),
    ('iPhone 13 Pro', 'Apple', 'Mobile Phones', 45),
    ('iPhone 13 Pro Max', 'Apple', 'Mobile Phones', 40),
    ('iPhone 12', 'Apple', 'Mobile Phones', 35),
    ('iPhone 12 Mini', 'Apple', 'Mobile Phones', 30),
    ('iPhone 12 Pro', 'Apple', 'Mobile Phones', 25),
    ('iPhone 12 Pro Max', 'Apple', 'Mobile Phones', 20),
    ('iPhone SE (2nd generation)', 'Apple', 'Mobile Phones', 15),
    ('iPhone 11', 'Apple', 'Mobile Phones', 10),
    ('iPhone 11 Pro', 'Apple', 'Mobile Phones', 5),
    ('iPhone 11 Pro Max', 'Apple', 'Mobile Phones', 50),
    ('iPhone XR', 'Apple', 'Mobile Phones', 45),
    ('iPhone XS', 'Apple', 'Mobile Phones', 40),
    ('iPhone XS Max', 'Apple', 'Mobile Phones', 35),
    ('iPhone X', 'Apple', 'Mobile Phones', 30),
    ('iPhone 8', 'Apple', 'Mobile Phones', 25),
    ('iPhone 8 Plus', 'Apple', 'Mobile Phones', 20),
    ('iPhone 7', 'Apple', 'Mobile Phones', 15),
    ('iPhone 7 Plus', 'Apple', 'Mobile Phones', 10),
    ('iPhone SE (1st generation)', 'Apple', 'Mobile Phones', 5),
    ('iPhone 6s', 'Apple', 'Mobile Phones', 50),
    ('iPhone 6s Plus', 'Apple', 'Mobile Phones', 45),
    ('iPhone 6', 'Apple', 'Mobile Phones', 40),
    ('iPhone 6 Plus', 'Apple', 'Mobile Phones', 35),
    ('iPhone 5s', 'Apple', 'Mobile Phones', 30),
    ('Samsung Galaxy S21 Ultra', 'Samsung', 'Mobile Phones', 50),
    ('Samsung Galaxy S21', 'Samsung', 'Mobile Phones', 45),
    ('Samsung Galaxy S21 Plus', 'Samsung', 'Mobile Phones', 40),
    ('Samsung Galaxy Note 20 Ultra', 'Samsung', 'Mobile Phones', 35),
    ('Samsung Galaxy Note 20', 'Samsung', 'Mobile Phones', 30),
    ('Samsung Galaxy S20 Ultra', 'Samsung', 'Mobile Phones', 25),
    ('Samsung Galaxy S20', 'Samsung', 'Mobile Phones', 20),
    ('Samsung Galaxy S20 Plus', 'Samsung', 'Mobile Phones', 15),
    ('Samsung Galaxy Z Fold 2', 'Samsung', 'Mobile Phones', 10),
    ('Samsung Galaxy Z Flip', 'Samsung', 'Mobile Phones', 5),
    ('Samsung Galaxy Z Flip 3', 'Samsung', 'Mobile Phones', 50),
    ('Samsung Galaxy Z Fold 3', 'Samsung', 'Mobile Phones', 45),
    ('Samsung Galaxy A72', 'Samsung', 'Mobile Phones', 40),
    ('Samsung Galaxy A52', 'Samsung', 'Mobile Phones', 35),
    ('Samsung Galaxy A32', 'Samsung', 'Mobile Phones', 30),
    ('Samsung Galaxy A12', 'Samsung', 'Mobile Phones', 25),
    ('Samsung Galaxy M51', 'Samsung', 'Mobile Phones', 20),
    ('Samsung Galaxy M31', 'Samsung', 'Mobile Phones', 15),
    ('Samsung Galaxy M21', 'Samsung', 'Mobile Phones', 10),
    ('Samsung Galaxy M11', 'Samsung', 'Mobile Phones', 5),
    ('Samsung Galaxy Tab S7', 'Samsung', 'Tablets', 40),
    ('Samsung Galaxy Tab S6 Lite', 'Samsung', 'Tablets', 35),
    ('Samsung Galaxy Tab A7', 'Samsung', 'Tablets', 30),
    ('Samsung Galaxy Tab S5e', 'Samsung', 'Tablets', 25),
    ('Samsung Galaxy Tab S7+', 'Samsung', 'Tablets', 20),
    ('Samsung Galaxy Tab S6', 'Samsung', 'Tablets', 15),
    ('Samsung Galaxy Tab S6 Lite', 'Samsung', 'Tablets', 10),
    ('Samsung Galaxy Tab A 10.1', 'Samsung', 'Tablets', 5),
    ('Samsung Galaxy Watch 4', 'Samsung', 'Smartwatches', 30),
    ('Samsung Galaxy Watch 4 Classic', 'Samsung', 'Smartwatches', 25),
    ('Samsung Galaxy Watch 3', 'Samsung', 'Smartwatches', 20),
    ('Samsung Galaxy Watch Active 2', 'Samsung', 'Smartwatches', 15),
    ('Samsung Galaxy Watch', 'Samsung', 'Smartwatches', 10),
    ('Samsung Galaxy Watch Active', 'Samsung', 'Smartwatches', 5),
    ('Samsung Galaxy Buds Pro', 'Samsung', 'Earbuds', 40),
    ('Samsung Galaxy Buds Live', 'Samsung', 'Earbuds', 35),
    ('Samsung Galaxy Buds+', 'Samsung', 'Earbuds', 30),
    ('Samsung Galaxy Buds', 'Samsung', 'Earbuds', 25),
    ('Samsung Galaxy Buds 2', 'Samsung', 'Earbuds', 20),
    ('Samsung Galaxy Buds Pro', 'Samsung', 'Earbuds', 15),
    ('Samsung Galaxy Buds Live', 'Samsung', 'Earbuds', 10),
    ('Samsung Galaxy Buds+', 'Samsung', 'Earbuds', 5),
    ('Samsung Galaxy Watch 4', 'Samsung', 'Smartwatches', 30),
    ('Samsung Galaxy Watch 4 Classic', 'Samsung', 'Smartwatches', 25),
    ('Samsung Galaxy Watch 3', 'Samsung', 'Smartwatches', 20),
    ('Samsung Galaxy Watch Active 2', 'Samsung', 'Smartwatches', 15),
    ('Samsung Galaxy Watch', 'Samsung', 'Smartwatches', 10),
    ('Samsung Galaxy Watch Active', 'Samsung', 'Smartwatches', 5),
    ('Samsung Galaxy Fit 2', 'Samsung', 'Fitness Bands', 40),
    ('Samsung Galaxy Fit', 'Samsung', 'Fitness Bands', 35),
    ('Samsung Galaxy Fit e', 'Samsung', 'Fitness Bands', 30),
    ('Samsung Galaxy Fit 2', 'Samsung', 'Fitness Bands', 25),
    ('Samsung Galaxy Fit', 'Samsung', 'Fitness Bands', 20),
    ('Samsung Galaxy Fit e', 'Samsung', 'Fitness Bands', 15),
    ('Samsung Galaxy Buds Fit', 'Samsung', 'Fitness Earbuds', 10),
    ('Samsung Galaxy Buds Fit', 'Samsung', 'Fitness Earbuds', 5),
    ('Vivo X70 Pro+', 'Vivo', 'Mobile Phones', 50),
    ('Vivo X70 Pro', 'Vivo', 'Mobile Phones', 45),
    ('Vivo X70', 'Vivo', 'Mobile Phones', 40),
    ('Vivo V21 5G', 'Vivo', 'Mobile Phones', 35),
    ('Vivo V21e', 'Vivo', 'Mobile Phones', 30),
    ('Vivo Y73s', 'Vivo', 'Mobile Phones', 25),
    ('Vivo Y72 5G', 'Vivo', 'Mobile Phones', 20),
    ('Vivo Y52s', 'Vivo', 'Mobile Phones', 15),
    ('Vivo Y51A', 'Vivo', 'Mobile Phones', 10),
    ('Vivo Y20A', 'Vivo', 'Mobile Phones', 5),
    ('Vivo T1 5G', 'Vivo', 'Mobile Phones', 50),
    ('Vivo S9 5G', 'Vivo', 'Mobile Phones', 45),
    ('Vivo Y76s 5G', 'Vivo', 'Mobile Phones', 40),
    ('Vivo Y54s 5G', 'Vivo', 'Mobile Phones', 35),
    ('Vivo X60 Pro+', 'Vivo', 'Mobile Phones', 30),
    ('Vivo X60 Pro', 'Vivo', 'Mobile Phones', 25),
    ('Vivo X60', 'Vivo', 'Mobile Phones', 20),
    ('Vivo V23 Pro 5G', 'Vivo', 'Mobile Phones', 15),
    ('Vivo V23e 5G', 'Vivo', 'Mobile Phones', 10),
    ('Vivo V23 5G', 'Vivo', 'Mobile Phones', 5),
    ('Vivo Y76 5G', 'Vivo', 'Mobile Phones', 50),
    ('Vivo Y72 5G', 'Vivo', 'Mobile Phones', 45),
    ('Vivo Y53s 5G', 'Vivo', 'Mobile Phones', 40),
    ('Vivo Y31s 5G', 'Vivo', 'Mobile Phones', 35),
    ('Vivo Y12s', 'Vivo', 'Mobile Phones', 30),
    ('Oppo Find X5 Pro', 'Oppo', 'Mobile Phones', 58),
    ('Oppo Reno7 Pro 5G', 'Oppo', 'Mobile Phones', 55),
    ('Oppo Reno7 5G', 'Oppo', 'Mobile Phones', 52),
    ('Oppo Reno6 Pro 5G', 'Oppo', 'Mobile Phones', 50),
    ('Oppo Reno6 5G', 'Oppo', 'Mobile Phones', 48),
    ('Oppo A95 5G', 'Oppo', 'Mobile Phones', 45),
    ('Oppo A74 5G', 'Oppo', 'Mobile Phones', 42),
    ('Oppo A56 5G', 'Oppo', 'Mobile Phones', 40),
    ('Oppo A16', 'Oppo', 'Mobile Phones', 38),
    ('Oppo A74', 'Oppo', 'Mobile Phones', 35),
    ('Oppo A54', 'Oppo', 'Mobile Phones', 33),
    ('Oppo A16s', 'Oppo', 'Mobile Phones', 30),
    ('Oppo A54s', 'Oppo', 'Mobile Phones', 28),
    ('Oppo A15', 'Oppo', 'Mobile Phones', 25),
    ('Oppo A16e', 'Oppo', 'Mobile Phones', 22),
    ('Oppo A16K', 'Oppo', 'Mobile Phones', 20),
    ('Oppo A74s', 'Oppo', 'Mobile Phones', 18),
    ('Oppo A16K Pro', 'Oppo', 'Mobile Phones', 15),
    ('Oppo A16K Core', 'Oppo', 'Mobile Phones', 12),
    ('Oppo F19 Pro+ 5G', 'Oppo', 'Mobile Phones', 50),
    ('Oppo F19 Pro', 'Oppo', 'Mobile Phones', 45),
    ('Oppo F19', 'Oppo', 'Mobile Phones', 40),
    ('Oppo F19s', 'Oppo', 'Mobile Phones', 35),
    ('Oppo F17 Pro', 'Oppo', 'Mobile Phones', 30),
    ('OnePlus 10 Pro', 'OnePlus', 'Mobile Phones', 52),
    ('OnePlus 9 Pro', 'OnePlus', 'Mobile Phones', 45),
    ('OnePlus 9', 'OnePlus', 'Mobile Phones', 42),
    ('OnePlus 9R', 'OnePlus', 'Mobile Phones', 40),
    ('OnePlus Nord 2', 'OnePlus', 'Mobile Phones', 38),
    ('OnePlus Nord CE 5G', 'OnePlus', 'Mobile Phones', 35),
    ('OnePlus Nord N200 5G', 'OnePlus', 'Mobile Phones', 33),
    ('OnePlus 8T', 'OnePlus', 'Mobile Phones', 30),
    ('OnePlus 8 Pro', 'OnePlus', 'Mobile Phones', 28),
    ('OnePlus 8', 'OnePlus', 'Mobile Phones', 25),
    ('OnePlus 8T+', 'OnePlus', 'Mobile Phones', 22),
    ('OnePlus 8T Pro', 'OnePlus', 'Mobile Phones', 20),
    ('OnePlus 7T Pro', 'OnePlus', 'Mobile Phones', 18),
    ('OnePlus 7T', 'OnePlus', 'Mobile Phones', 15),
    ('OnePlus 7 Pro', 'OnePlus', 'Mobile Phones', 12),
    ('OnePlus 7', 'OnePlus', 'Mobile Phones', 10),
    ('OnePlus 6T', 'OnePlus', 'Mobile Phones', 8),
    ('OnePlus 6', 'OnePlus', 'Mobile Phones', 5),
    ('OnePlus 5T', 'OnePlus', 'Mobile Phones', 12),
    ('OnePlus 5', 'OnePlus', 'Mobile Phones', 10),
    ('OnePlus 3T', 'OnePlus', 'Mobile Phones', 8),
    ('OnePlus 3', 'OnePlus', 'Mobile Phones', 5),
    ('OnePlus 2', 'OnePlus', 'Mobile Phones', 12),
    ('OnePlus One', 'OnePlus', 'Mobile Phones', 10),
    ('OnePlus X', 'OnePlus', 'Mobile Phones', 8),
    ('Realme GT 2 Pro', 'Realme', 'Mobile Phones', 47),
    ('Realme GT 2', 'Realme', 'Mobile Phones', 45),
    ('Realme GT Neo 3', 'Realme', 'Mobile Phones', 42),
    ('Realme GT Neo 2', 'Realme', 'Mobile Phones', 40),
    ('Realme GT Master Edition', 'Realme', 'Mobile Phones', 38),
    ('Realme 9 Pro+', 'Realme', 'Mobile Phones', 35),
    ('Realme 9 Pro', 'Realme', 'Mobile Phones', 33),
    ('Realme 9', 'Realme', 'Mobile Phones', 30),
    ('Realme 9i', 'Realme', 'Mobile Phones', 28),
    ('Realme 8 Pro', 'Realme', 'Mobile Phones', 25),
    ('Realme 8', 'Realme', 'Mobile Phones', 22),
    ('Realme 8i', 'Realme', 'Mobile Phones', 20),
    ('Realme 8s', 'Realme', 'Mobile Phones', 18),
    ('Realme 7 Pro', 'Realme', 'Mobile Phones', 15),
    ('Realme 7', 'Realme', 'Mobile Phones', 12),
    ('Realme 7i', 'Realme', 'Mobile Phones', 10),
    ('Realme 7s', 'Realme', 'Mobile Phones', 8),
    ('Realme 6 Pro', 'Realme', 'Mobile Phones', 25),
    ('Realme 6', 'Realme', 'Mobile Phones', 22),
    ('Realme 6i', 'Realme', 'Mobile Phones', 20),
    ('Realme 6s', 'Realme', 'Mobile Phones', 18),
    ('Realme 5 Pro', 'Realme', 'Mobile Phones', 15),
    ('Realme 5', 'Realme', 'Mobile Phones', 12),
    ('Realme 5s', 'Realme', 'Mobile Phones', 10),
    ('Redmi Note 11 Pro', 'Redmi', 'Mobile Phones', 48),
    ('Redmi Note 11', 'Redmi', 'Mobile Phones', 45),
    ('Redmi Note 11S', 'Redmi', 'Mobile Phones', 42),
    ('Redmi Note 11T', 'Redmi', 'Mobile Phones', 40),
    ('Redmi Note 11 4G', 'Redmi', 'Mobile Phones', 38),
    ('Redmi Note 11 Pro+', 'Redmi', 'Mobile Phones', 35),
    ('Redmi Note 11 5G', 'Redmi', 'Mobile Phones', 33),
    ('Redmi 10', 'Redmi', 'Mobile Phones', 30),
    ('Redmi 10 Prime', 'Redmi', 'Mobile Phones', 28),
    ('Redmi 10A', 'Redmi', 'Mobile Phones', 25),
    ('Redmi 9T', 'Redmi', 'Mobile Phones', 22),
    ('Redmi 9 Power', 'Redmi', 'Mobile Phones', 20),
    ('Redmi 9A', 'Redmi', 'Mobile Phones', 18),
    ('Redmi 9C', 'Redmi', 'Mobile Phones', 15),
    ('Redmi Note 10 Pro', 'Redmi', 'Mobile Phones', 12),
    ('Redmi Note 10', 'Redmi', 'Mobile Phones', 10),
    ('Redmi Note 10S', 'Redmi', 'Mobile Phones', 8),
    ('Redmi Note 10 5G', 'Redmi', 'Mobile Phones', 25),
    ('Redmi K40 Gaming Edition', 'Redmi', 'Mobile Phones', 22),
    ('Redmi K40', 'Redmi', 'Mobile Phones', 20),
    ('Redmi K40 Pro', 'Redmi', 'Mobile Phones', 18),
    ('Redmi K40 Pro+', 'Redmi', 'Mobile Phones', 15),
    ('Redmi K30 Ultra', 'Redmi', 'Mobile Phones', 12),
    ('Redmi K30S Ultra', 'Redmi', 'Mobile Phones', 10),
    ('Nokia G50', 'Nokia', 'Mobile Phones', 42),
    ('Nokia G21', 'Nokia', 'Mobile Phones', 40),
    ('Nokia G10', 'Nokia', 'Mobile Phones', 38),
    ('Nokia G20', 'Nokia', 'Mobile Phones', 35),
    ('Nokia XR20', 'Nokia', 'Mobile Phones', 33),
    ('Nokia 5.4', 'Nokia', 'Mobile Phones', 30),
    ('Nokia 3.4', 'Nokia', 'Mobile Phones', 28),
    ('Nokia 2.4', 'Nokia', 'Mobile Phones', 25),
    ('Nokia 8.3 5G', 'Nokia', 'Mobile Phones', 22),
    ('Nokia 5.3', 'Nokia', 'Mobile Phones', 20),
    ('Nokia 7.2', 'Nokia', 'Mobile Phones', 18),
    ('Nokia 6.2', 'Nokia', 'Mobile Phones', 15),
    ('Nokia 9 PureView', 'Nokia', 'Mobile Phones', 12),
    ('Nokia 8.1', 'Nokia', 'Mobile Phones', 10),
    ('Nokia 7 Plus', 'Nokia', 'Mobile Phones', 8),
    ('Nokia 6.1', 'Nokia', 'Mobile Phones', 25),
    ('Nokia 5.1', 'Nokia', 'Mobile Phones', 22),
    ('Nokia 3.1', 'Nokia', 'Mobile Phones', 20),
    ('Nokia 2.1', 'Nokia', 'Mobile Phones', 18),
    ('Nokia 1.4', 'Nokia', 'Mobile Phones', 15),
    ('Nokia 1 Plus', 'Nokia', 'Mobile Phones', 12),
    ('Nokia 8 Sirocco', 'Nokia', 'Mobile Phones', 10),
    ('Nokia 7.1', 'Nokia', 'Mobile Phones', 8),
    ('Nokia 6.1 Plus', 'Nokia', 'Mobile Phones', 25),
    ('Nokia 5.1 Plus', 'Nokia', 'Mobile Phones', 22),
    ('Motorola Edge 20', 'Motorola', 'Mobile Phones', 42),
    ('Motorola Edge 20 Pro', 'Motorola', 'Mobile Phones', 40),
    ('Motorola Edge 20 Lite', 'Motorola', 'Mobile Phones', 38),
    ('Motorola Moto G Pure', 'Motorola', 'Mobile Phones', 35),
    ('Motorola Moto G Power (2021)', 'Motorola', 'Mobile Phones', 33),
    ('Motorola Moto G Stylus (2021)', 'Motorola', 'Mobile Phones', 30),
    ('Motorola Moto G30', 'Motorola', 'Mobile Phones', 28),
    ('Motorola Moto G10', 'Motorola', 'Mobile Phones', 25),
    ('Motorola Moto G9 Power', 'Motorola', 'Mobile Phones', 22),
    ('Motorola Moto G9 Play', 'Motorola', 'Mobile Phones', 20),
    ('Motorola Moto G9 Plus', 'Motorola', 'Mobile Phones', 18),
    ('Motorola Moto G8 Power', 'Motorola', 'Mobile Phones', 15),
    ('Motorola Moto G8 Plus', 'Motorola', 'Mobile Phones', 12),
    ('Motorola Moto G8', 'Motorola', 'Mobile Phones', 10),
    ('Motorola Moto G7 Power', 'Motorola', 'Mobile Phones', 8),
    ('Motorola Moto G7 Play', 'Motorola', 'Mobile Phones', 25),
    ('Motorola Moto G7 Plus', 'Motorola', 'Mobile Phones', 22),
    ('Motorola Moto G7', 'Motorola', 'Mobile Phones', 20),
    ('Motorola Moto G6 Plus', 'Motorola', 'Mobile Phones', 18),
    ('Motorola Moto G6', 'Motorola', 'Mobile Phones', 15),
    ('Motorola Moto G6 Play', 'Motorola', 'Mobile Phones', 12),
    ('Motorola Moto G5S Plus', 'Motorola', 'Mobile Phones', 10),
    ('Motorola Moto G5S', 'Motorola', 'Mobile Phones', 8),
    ('Motorola Moto G5 Plus', 'Motorola', 'Mobile Phones', 25),
    ('Motorola Moto G5', 'Motorola', 'Mobile Phones', 22),
    ('Panasonic CS/CU-NU09VKYW 0.8 Ton 3 Star Inverter Split AC', 'Panasonic', 'Air Conditioners', 30),
    ('Panasonic CS/CU-NU12VKYW 1 Ton 4 Star Inverter Split AC', 'Panasonic', 'Air Conditioners', 25),
    ('Panasonic CS/CU-NU18VKYW 1.5 Ton 4 Star Inverter Split AC', 'Panasonic', 'Air Conditioners', 20),
    ('Panasonic CS/CU-NU24VKYW 2 Ton 4 Star Inverter Split AC', 'Panasonic', 'Air Conditioners', 15),
    ('Panasonic CS/CU-NU12VKYW 1 Ton 5 Star Inverter Split AC', 'Panasonic', 'Air Conditioners', 10),
    ('Panasonic CS/CU-NU18VKYW 1.5 Ton 5 Star Inverter Split AC', 'Panasonic', 'Air Conditioners', 5),
    ('Panasonic CS/CU-NU24VKYW 2 Ton 5 Star Inverter Split AC', 'Panasonic', 'Air Conditioners', 30),
    ('Panasonic CS/CU-NU09XKYW 0.8 Ton 3 Star Split AC', 'Panasonic', 'Air Conditioners', 25),
    ('Panasonic CS/CU-NU12XKYW 1 Ton 3 Star Split AC', 'Panasonic', 'Air Conditioners', 20),
    ('Panasonic CS/CU-NU18XKYW 1.5 Ton 3 Star Split AC', 'Panasonic', 'Air Conditioners', 15),
    ('Panasonic CS/CU-NU24XKYW 2 Ton 3 Star Split AC', 'Panasonic', 'Air Conditioners', 10),
    ('Panasonic CS/CU-NU09YKYW 0.8 Ton 5 Star Split AC', 'Panasonic', 'Air Conditioners', 5),
    ('Panasonic CS/CU-NU12YKYW 1 Ton 5 Star Split AC', 'Panasonic', 'Air Conditioners', 30),
    ('Panasonic CS/CU-NU18YKYW 1.5 Ton 5 Star Split AC', 'Panasonic', 'Air Conditioners', 25),
    ('Panasonic CS/CU-NU24YKYW 2 Ton 5 Star Split AC', 'Panasonic', 'Air Conditioners', 20),
    ('Panasonic CS/CU-SU09VKYW 0.8 Ton 3 Star Split AC', 'Panasonic', 'Air Conditioners', 15),
    ('Panasonic CS/CU-SU12VKYW 1 Ton 3 Star Split AC', 'Panasonic', 'Air Conditioners', 10),
    ('Panasonic CS/CU-SU18VKYW 1.5 Ton 3 Star Split AC', 'Panasonic', 'Air Conditioners', 5),
    ('Panasonic CS/CU-SU24VKYW 2 Ton 3 Star Split AC', 'Panasonic', 'Air Conditioners', 30),
    ('Panasonic CS/CU-SU09XKYW 0.8 Ton 4 Star Split AC', 'Panasonic', 'Air Conditioners', 25),
    ('Panasonic CS/CU-SU12XKYW 1 Ton 4 Star Split AC', 'Panasonic', 'Air Conditioners', 20),
    ('Panasonic CS/CU-SU18XKYW 1.5 Ton 4 Star Split AC', 'Panasonic', 'Air Conditioners', 15),
    ('Panasonic CS/CU-SU24XKYW 2 Ton 4 Star Split AC', 'Panasonic', 'Air Conditioners', 10),
    ('Panasonic CS/CU-SU09YKYW 0.8 Ton 5 Star Split AC', 'Panasonic', 'Air Conditioners', 5),
    ('Godrej GIC 12HTC5-WTA 1 Ton 5 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 30),
    ('Godrej GIC 18SOTC3-WTA 1.5 Ton 3 Star Split AC', 'Godrej', 'Air Conditioners', 25),
    ('Godrej GIC 24RTC3-WSA 2 Ton 3 Star Split AC', 'Godrej', 'Air Conditioners', 20),
    ('Godrej GIC 18YTC3-WTA 1.5 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 15),
    ('Godrej GIC 12FTC3-WSA 1 Ton 3 Star Split AC', 'Godrej', 'Air Conditioners', 10),
    ('Godrej GIC 12RTC3-WSA 1 Ton 3 Star Split AC', 'Godrej', 'Air Conditioners', 5),
    ('Godrej GIC 18WTC3-WTA 1.5 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 30),
    ('Godrej GIC 24BTB3-WRA 2 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 25),
    ('Godrej GIC 12NTC3-WTA 1 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 20),
    ('Godrej GIC 18LTC3-WSA 1.5 Ton 3 Star Split AC', 'Godrej', 'Air Conditioners', 15),
    ('Godrej GIC 24GTC3-WTA 2 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 10),
    ('Godrej GIC 18WTC3-WTA 1.5 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 5),
    ('Godrej GIC 12GTC3-WSA 1 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 30),
    ('Godrej GIC 24DTB3-WRA 2 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 25),
    ('Godrej GIC 18STC3-WTA 1.5 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 20),
    ('Godrej GIC 12FTC3-WTA 1 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 15),
    ('Godrej GIC 12FTC3-WTA 1 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 10),
    ('Godrej GIC 18FTC3-WSA 1.5 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 5),
    ('Godrej GIC 24FTC3-WSA 2 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 30),
    ('Godrej GIC 18OTC3-WSA 1.5 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 25),
    ('LG KS-Q12YNZA 1 Ton 5 Star Inverter Split AC', 'LG', 'Air Conditioners', 30),
    ('LG KS-Q18YNZA 1.5 Ton 5 Star Inverter Split AC', 'LG', 'Air Conditioners', 25),
    ('LG KS-Q24YNXA 2 Ton 5 Star Inverter Split AC', 'LG', 'Air Conditioners', 20),
    ('LG KS-Q12HNZD 1 Ton 5 Star Hot and Cold Inverter Split AC', 'LG', 'Air Conditioners', 15),
    ('LG KS-Q18HNZD 1.5 Ton 5 Star Hot and Cold Inverter Split AC', 'LG', 'Air Conditioners', 10),
    ('LG KS-Q24ENXA 2 Ton 5 Star Inverter Split AC', 'LG', 'Air Conditioners', 5),
    ('LG MS-Q18YNZA 1.5 Ton 3 Star Inverter Split AC', 'LG', 'Air Conditioners', 30),
    ('LG MS-Q12YNZA 1 Ton 3 Star Inverter Split AC', 'LG', 'Air Conditioners', 25),
    ('LG KS-Q18GWZD 1.5 Ton 5 Star Inverter Split AC', 'LG', 'Air Conditioners', 20),
    ('LG KS-Q24GWZD 2 Ton 5 Star Inverter Split AC', 'LG', 'Air Conditioners', 15),
    ('LG KS-Q18HNXD 1.5 Ton 3 Star Hot and Cold Inverter Split AC', 'LG', 'Air Conditioners', 10),
    ('LG KS-Q12YNXA 1 Ton 5 Star Inverter Split AC', 'LG', 'Air Conditioners', 5),
    ('LG MS-Q18KNZA 1.5 Ton 3 Star Inverter Split AC', 'LG', 'Air Conditioners', 30),
    ('LG MS-Q12KNZA 1 Ton 3 Star Inverter Split AC', 'LG', 'Air Conditioners', 25),
    ('LG KS-Q18ENZA 1.5 Ton 5 Star Inverter Split AC', 'LG', 'Air Conditioners', 20),
    ('LG KS-Q12GWZD 1 Ton 5 Star Inverter Split AC', 'LG', 'Air Conditioners', 15),
    ('LG KS-Q12AWZD 1 Ton 5 Star Inverter Split AC', 'LG', 'Air Conditioners', 10),
    ('LG KS-Q18YNXA 1.5 Ton 5 Star Inverter Split AC', 'LG', 'Air Conditioners', 5),
    ('LG KS-Q24FNXD 2 Ton 3 Star Hot and Cold Inverter Split AC', 'LG', 'Air Conditioners', 30),
    ('Samsung AR18AYLYATNNA 1.5 Ton 5 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 30),
    ('Samsung AR18TV3JFMCNNA 1.5 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 25),
    ('Samsung AR18TY3QBBUNNA 1.5 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 20),
    ('Samsung AR12AYLYATNNA 1 Ton 5 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 15),
    ('Samsung AR18TY3QCBUNNA 1.5 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 10),
    ('Samsung AR18TY3QBBUNNA 1.5 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 5),
    ('Samsung AR24AYLYATNNA 2 Ton 5 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 30),
    ('Samsung AR18TY3QCBUNNA 1.5 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 25),
    ('Samsung AR18TV3HFTZNA 1.5 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 20),
    ('Samsung AR12TY3QBBUNNA 1 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 15),
    ('Samsung AR12TV3HFTZNA 1 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 10),
    ('Samsung AR18TY3QBBUNNA 1.5 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 5),
    ('Samsung AR18AYLYATNNA 1.5 Ton 5 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 30),
    ('Samsung AR18TV3JFMCNNA 1.5 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 25),
    ('Samsung AR18TY3QBBUNNA 1.5 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 20),
    ('Samsung AR12AYLYATNNA 1 Ton 5 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 15),
    ('Samsung AR18TY3QCBUNNA 1.5 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 10),
    ('Samsung AR18TY3QBBUNNA 1.5 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 5),
    ('Samsung AR24AYLYATNNA 2 Ton 5 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 30),
    ('Samsung AR18TY3QCBUNNA 1.5 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 25),
    ('Panasonic TH-43HX635DX 43 inch UHD Smart LED TV', 'Panasonic', 'Televisions', 30),
    ('Panasonic TH-32HS625DX 32 inch HD Ready Smart LED TV', 'Panasonic', 'Televisions', 25),
    ('Panasonic TH-58HX450DX 58 inch Ultra HD 4K Smart LED TV', 'Panasonic', 'Televisions', 20),
    ('Panasonic TH-43HX635DX 43 inch UHD Smart LED TV', 'Panasonic', 'Televisions', 15),
    ('Panasonic TH-40HS450DX 40 inch Full HD Smart LED TV', 'Panasonic', 'Televisions', 10),
    ('Panasonic TH-43HS655DX 43 inch Full HD Smart LED TV', 'Panasonic', 'Televisions', 5),
    ('Panasonic TH-50HX635DX 50 inch UHD Smart LED TV', 'Panasonic', 'Televisions', 30),
    ('Panasonic TH-32JS660DX 32 inch HD Ready Smart LED TV', 'Panasonic', 'Televisions', 25),
    ('Panasonic TH-43HS700DX 43 inch Full HD Smart LED TV', 'Panasonic', 'Televisions', 20),
    ('Panasonic TH-43HS700DX 43 inch Full HD Smart LED TV', 'Panasonic', 'Televisions', 15),
    ('Panasonic TH-32JS660DX 32 inch HD Ready Smart LED TV', 'Panasonic', 'Televisions', 10),
    ('Panasonic TH-32JS660DX 32 inch HD Ready Smart LED TV', 'Panasonic', 'Televisions', 5),
    ('Panasonic TH-43HX635DX 43 inch UHD Smart LED TV', 'Panasonic', 'Televisions', 30),
    ('Panasonic TH-32HS625DX 32 inch HD Ready Smart LED TV', 'Panasonic', 'Televisions', 25),
    ('Panasonic TH-58HX450DX 58 inch Ultra HD 4K Smart LED TV', 'Panasonic', 'Televisions', 20),
    ('Panasonic TH-43HX635DX 43 inch UHD Smart LED TV', 'Panasonic', 'Televisions', 15),
    ('Panasonic TH-40HS450DX 40 inch Full HD Smart LED TV', 'Panasonic', 'Televisions', 10),
    ('Panasonic TH-43HS655DX 43 inch Full HD Smart LED TV', 'Panasonic', 'Televisions', 5),
    ('Panasonic TH-50HX635DX 50 inch UHD Smart LED TV', 'Panasonic', 'Televisions', 30),
    ('Panasonic TH-32JS660DX 32 inch HD Ready Smart LED TV', 'Panasonic', 'Televisions', 25),
    ('LG 43UM7290PTF 43 inch Ultra HD 4K LED Smart TV', 'LG', 'Televisions', 30),
    ('LG 32LM636BPTB 32 inch HD Ready LED Smart TV', 'LG', 'Televisions', 25),
    ('LG 55UM7290PTD 55 inch Ultra HD 4K LED Smart TV', 'LG', 'Televisions', 20),
    ('LG 43LM5650PTA 43 inch Full HD LED Smart TV', 'LG', 'Televisions', 15),
    ('LG 32LM563BPTC 32 inch HD Ready LED Smart TV', 'LG', 'Televisions', 10),
    ('LG 43UM7290PTF 43 inch Ultra HD 4K LED Smart TV', 'LG', 'Televisions', 5),
    ('LG 50UN7300PTC 50 inch Ultra HD 4K LED Smart TV', 'LG', 'Televisions', 30),
    ('LG 32LM636BPTB 32 inch HD Ready LED Smart TV', 'LG', 'Televisions', 25),
    ('LG 55UM7290PTD 55 inch Ultra HD 4K LED Smart TV', 'LG', 'Televisions', 20),
    ('LG 43LM5650PTA 43 inch Full HD LED Smart TV', 'LG', 'Televisions', 15),
    ('LG 32LM563BPTC 32 inch HD Ready LED Smart TV', 'LG', 'Televisions', 10),
    ('LG 43UM7290PTF 43 inch Ultra HD 4K LED Smart TV', 'LG', 'Televisions', 5),
    ('LG 50UN7300PTC 50 inch Ultra HD 4K LED Smart TV', 'LG', 'Televisions', 30),
    ('LG 32LM636BPTB 32 inch HD Ready LED Smart TV', 'LG', 'Televisions', 25),
    ('LG 55UM7290PTD 55 inch Ultra HD 4K LED Smart TV', 'LG', 'Televisions', 20),
    ('LG 43LM5650PTA 43 inch Full HD LED Smart TV', 'LG', 'Televisions', 15),
    ('LG 32LM563BPTC 32 inch HD Ready LED Smart TV', 'LG', 'Televisions', 10),
    ('LG 43UM7290PTF 43 inch Ultra HD 4K LED Smart TV', 'LG', 'Televisions', 5),
    ('LG 50UN7300PTC 50 inch Ultra HD 4K LED Smart TV', 'LG', 'Televisions', 30),
    ('Samsung UA32T4340AKXXL 32 inch HD Ready LED TV', 'Samsung', 'Televisions', 30),
    ('Samsung UA43T5470AKXXL 43 inch Ultra HD 4K Smart LED TV', 'Samsung', 'Televisions', 25),
    ('Samsung UA50TUE60AKXXL 50 inch Ultra HD 4K LED TV', 'Samsung', 'Televisions', 20),
    ('Samsung UA55TU8000KXXL 55 inch Ultra HD 4K LED Smart TV', 'Samsung', 'Televisions', 15),
    ('Samsung UA43T5350AKXXL 43 inch Full HD LED Smart TV', 'Samsung', 'Televisions', 10),
    ('Samsung UA32T4300DKXXL 32 inch HD Ready LED TV', 'Samsung', 'Televisions', 5),
    ('Samsung UA43T5470AKXXL 43 inch Ultra HD 4K Smart LED TV', 'Samsung', 'Televisions', 30),
    ('Samsung UA50TUE60AKXXL 50 inch Ultra HD 4K LED TV', 'Samsung', 'Televisions', 25),
    ('Samsung UA55TU8000KXXL 55 inch Ultra HD 4K LED Smart TV', 'Samsung', 'Televisions', 20),
    ('Samsung UA43T5350AKXXL 43 inch Full HD LED Smart TV', 'Samsung', 'Televisions', 15),
    ('Samsung UA32T4300DKXXL 32 inch HD Ready LED TV', 'Samsung', 'Televisions', 10),
    ('Samsung UA43T5470AKXXL 43 inch Ultra HD 4K Smart LED TV', 'Samsung', 'Televisions', 5),
    ('Samsung UA50TUE60AKXXL 50 inch Ultra HD 4K LED TV', 'Samsung', 'Televisions', 30),
    ('Samsung UA55TU8000KXXL 55 inch Ultra HD 4K LED Smart TV', 'Samsung', 'Televisions', 25),
    ('Samsung UA43T5350AKXXL 43 inch Full HD LED Smart TV', 'Samsung', 'Televisions', 20),
    ('Samsung UA32T4300DKXXL 32 inch HD Ready LED TV', 'Samsung', 'Televisions', 15),
    ('Samsung UA43T5470AKXXL 43 inch Ultra HD 4K Smart LED TV', 'Samsung', 'Televisions', 10),
    ('Samsung UA50TUE60AKXXL 50 inch Ultra HD 4K LED TV', 'Samsung', 'Televisions', 5),
    ('Samsung UA55TU8000KXXL 55 inch Ultra HD 4K LED Smart TV', 'Samsung', 'Televisions', 30),
    ('HP Pavilion 15-eg0103TX 15.6 inch FHD Laptop', 'HP', 'Laptops', 30),
    ('HP Pavilion x360 14-dh1178TU 14 inch FHD Touchscreen Laptop', 'HP', 'Laptops', 25),
    ('HP 15s-du3047TX 15.6 inch FHD Laptop', 'HP', 'Laptops', 20),
    ('HP Pavilion Gaming 15-dk0261TX 15.6 inch FHD Laptop', 'HP', 'Laptops', 15),
    ('HP Envy x360 Convertible 13-ay0078AU 13.3 inch FHD Touchscreen Laptop', 'HP', 'Laptops', 10),
    ('HP Omen 15-ek0019TX 15.6 inch FHD Gaming Laptop', 'HP', 'Laptops', 5),
    ('HP Pavilion 15-eg0103TX 15.6 inch FHD Laptop', 'HP', 'Laptops', 30),
    ('HP Pavilion x360 14-dh1178TU 14 inch FHD Touchscreen Laptop', 'HP', 'Laptops', 25),
    ('HP 15s-du3047TX 15.6 inch FHD Laptop', 'HP', 'Laptops', 20),
    ('HP Pavilion Gaming 15-dk0261TX 15.6 inch FHD Laptop', 'HP', 'Laptops', 15),
    ('HP Envy x360 Convertible 13-ay0078AU 13.3 inch FHD Touchscreen Laptop', 'HP', 'Laptops', 10),
    ('HP Omen 15-ek0019TX 15.6 inch FHD Gaming Laptop', 'HP', 'Laptops', 5),
    ('HP Pavilion 15-eg0103TX 15.6 inch FHD Laptop', 'HP', 'Laptops', 30),
    ('HP Pavilion x360 14-dh1178TU 14 inch FHD Touchscreen Laptop', 'HP', 'Laptops', 25),
    ('HP 15s-du3047TX 15.6 inch FHD Laptop', 'HP', 'Laptops', 20),
    ('HP Pavilion Gaming 15-dk0261TX 15.6 inch FHD Laptop', 'HP', 'Laptops', 15),
    ('HP Envy x360 Convertible 13-ay0078AU 13.3 inch FHD Touchscreen Laptop', 'HP', 'Laptops', 10),
    ('HP Omen 15-ek0019TX 15.6 inch FHD Gaming Laptop', 'HP', 'Laptops', 5),
    ('HP Pavilion 15-eg0103TX 15.6 inch FHD Laptop', 'HP', 'Laptops', 30),
    ('HP Pavilion x360 14-dh1178TU 14 inch FHD Touchscreen Laptop', 'HP', 'Laptops', 25),
    ('HP Envy 15-ep0142TX 15.6 inch 4K UHD Laptop', 'HP', 'Laptops', 30),
    ('HP Spectre x360 13-aw0053TU 13.3 inch 4K UHD Touchscreen Laptop', 'HP', 'Laptops', 25),
    ('HP Pavilion Gaming 16-a0055TX 16.1 inch FHD Gaming Laptop', 'HP', 'Laptops', 20),
    ('HP Spectre x360 14-ea0064TU 13.5 inch 3K2K Touchscreen Laptop', 'HP', 'Laptops', 15),
    ('HP Omen 17-cb0079TX 17.3 inch FHD Gaming Laptop', 'HP', 'Laptops', 10),
    ('Dell XPS 13 9310 13.4 inch FHD+ Touchscreen Laptop', 'Dell', 'Laptops', 30),
    ('Dell Inspiron 5406 14 inch FHD Touchscreen 2in1 Laptop', 'Dell', 'Laptops', 25),
    ('Dell G3 3500 15.6 inch FHD Gaming Laptop', 'Dell', 'Laptops', 20),
    ('Dell XPS 15 9500 15.6 inch UHD+ Touchscreen Laptop', 'Dell', 'Laptops', 15),
    ('Dell Inspiron 7501 15.6 inch FHD Laptop', 'Dell', 'Laptops', 10),
    ('Dell Alienware m15 R4 15.6 inch FHD Gaming Laptop', 'Dell', 'Laptops', 5),
    ('Dell Latitude 3410 14 inch HD Laptop', 'Dell', 'Laptops', 30),
    ('Dell Precision 3551 15.6 inch FHD Mobile Workstation Laptop', 'Dell', 'Laptops', 25),
    ('Dell Vostro 3400 14 inch FHD Laptop', 'Dell', 'Laptops', 20),
    ('Dell Inspiron 3501 15.6 inch HD Laptop', 'Dell', 'Laptops', 15),
    ('Dell Latitude 5420 14 inch FHD Laptop', 'Dell', 'Laptops', 10),
    ('Dell XPS 17 9700 17 inch UHD+ Touchscreen Laptop', 'Dell', 'Laptops', 5),
    ('Dell Inspiron 3593 15.6 inch FHD Laptop', 'Dell', 'Laptops', 30),
    ('Dell Precision 5550 15.6 inch UHD+ Mobile Workstation Laptop', 'Dell', 'Laptops', 25),
    ('Dell Alienware m17 R4 17.3 inch FHD Gaming Laptop', 'Dell', 'Laptops', 20),
    ('Dell Inspiron 5402 14 inch FHD Laptop', 'Dell', 'Laptops', 15),
    ('Dell Latitude 7420 14 inch FHD Laptop', 'Dell', 'Laptops', 10),
    ('Dell Vostro 3500 15.6 inch FHD Laptop', 'Dell', 'Laptops', 5),
    ('Dell Inspiron 5505 15.6 inch FHD Laptop', 'Dell', 'Laptops', 30),
    ('Dell Precision 7550 15.6 inch UHD+ Mobile Workstation Laptop', 'Dell', 'Laptops', 25),
    ('Dell XPS 13 9305 13.3 inch FHD+ Laptop', 'Dell', 'Laptops', 20),
    ('Dell Alienware Area-51m R2 17.3 inch FHD Gaming Laptop', 'Dell', 'Laptops', 15),
    ('Dell Inspiron 3593 15.6 inch HD Laptop', 'Dell', 'Laptops', 10),
    ('Dell Latitude 5401 14 inch FHD Laptop', 'Dell', 'Laptops', 5),
    ('Dell G5 15 5500 15.6 inch FHD Gaming Laptop', 'Dell', 'Laptops', 30),
    ('LG GL-I292RPZL 260 L 4 Star Double Door Refrigerator', 'LG', 'Refrigerators', 30),
    ('LG GL-D201ARGY 190 L 4 Star Single Door Refrigerator', 'LG', 'Refrigerators', 25),
    ('LG GL-Q292SDSY 260 L 2 Star Double Door Refrigerator', 'LG', 'Refrigerators', 20),
    ('LG GL-T292SRGY 260 L 3 Star Double Door Refrigerator', 'LG', 'Refrigerators', 15),
    ('LG GL-C292SPZU 260 L 2 Star Double Door Refrigerator', 'LG', 'Refrigerators', 10),
    ('LG GL-E201ASRY 190 L 4 Star Single Door Refrigerator', 'LG', 'Refrigerators', 5),
    ('LG GL-I292RPZY 260 L 4 Star Double Door Refrigerator', 'LG', 'Refrigerators', 30),
    ('LG GL-D201APZY 190 L 4 Star Single Door Refrigerator', 'LG', 'Refrigerators', 25),
    ('LG GL-Q292SDSY 260 L 2 Star Double Door Refrigerator', 'LG', 'Refrigerators', 20),
    ('LG GL-T292SRGY 260 L 3 Star Double Door Refrigerator', 'LG', 'Refrigerators', 15),
    ('LG GL-C292SPZU 260 L 2 Star Double Door Refrigerator', 'LG', 'Refrigerators', 10),
    ('LG GL-E201ASRY 190 L 4 Star Single Door Refrigerator', 'LG', 'Refrigerators', 5),
    ('LG GL-I292RPZY 260 L 4 Star Double Door Refrigerator', 'LG', 'Refrigerators', 30),
    ('LG GL-D201APZY 190 L 4 Star Single Door Refrigerator', 'LG', 'Refrigerators', 25),
    ('LG GL-Q292SDSY 260 L 2 Star Double Door Refrigerator', 'LG', 'Refrigerators', 20),
    ('LG GL-T292SRGY 260 L 3 Star Double Door Refrigerator', 'LG', 'Refrigerators', 15),
    ('LG GL-C292SPZU 260 L 2 Star Double Door Refrigerator', 'LG', 'Refrigerators', 10),
    ('LG GL-E201ASRY 190 L 4 Star Single Door Refrigerator', 'LG', 'Refrigerators', 5),
    ('LG GL-I292RPZY 260 L 4 Star Double Door Refrigerator', 'LG', 'Refrigerators', 30),
    ('LG GL-D201APZY 190 L 4 Star Single Door Refrigerator', 'LG', 'Refrigerators', 25),
    ('LG GL-Q292SDSY 260 L 2 Star Double Door Refrigerator', 'LG', 'Refrigerators', 20),
    ('LG GL-T292SRGY 260 L 3 Star Double Door Refrigerator', 'LG', 'Refrigerators', 15),
    ('LG GL-C292SPZU 260 L 2 Star Double Door Refrigerator', 'LG', 'Refrigerators', 10),
    ('LG GL-E201ASRY 190 L 4 Star Single Door Refrigerator', 'LG', 'Refrigerators', 5),
    ('LG GL-I292RPZY 260 L 4 Star Double Door Refrigerator', 'LG', 'Refrigerators', 30),
    ('Panasonic NR-BL349VSX1 342 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 30),
    ('Panasonic NR-BL459VSX2 432 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 25),
    ('Panasonic NR-BL569VSX3 532 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 20),
    ('Panasonic NR-BL689VSX4 632 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 15),
    ('Panasonic NR-BL799VSX5 732 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 10),
    ('Panasonic NR-BL899VSX6 832 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 5),
    ('Panasonic NR-BL349VSX7 342 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 30),
    ('Panasonic NR-BL459VSX8 432 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 25),
    ('Panasonic NR-BL569VSX9 532 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 20),
    ('Panasonic NR-BL689VSX10 632 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 15),
    ('Panasonic NR-BL799VSX11 732 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 10),
    ('Panasonic NR-BL899VSX12 832 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 5),
    ('Panasonic NR-BL349VSX13 342 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 30),
    ('Panasonic NR-BL459VSX14 432 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 25),
    ('Panasonic NR-BL569VSX15 532 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 20),
    ('Panasonic NR-BL689VSX16 632 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 15),
    ('Panasonic NR-BL799VSX17 732 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 10),
    ('Panasonic NR-BL899VSX18 832 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 5),
    ('Panasonic NR-BL349VSX19 342 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 30),
    ('Panasonic NR-BL459VSX20 432 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 25),
    ('Panasonic NR-BL569VSX21 532 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 20),
    ('Panasonic NR-BL689VSX22 632 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 15),
    ('Panasonic NR-BL799VSX23 732 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 10),
    ('Panasonic NR-BL899VSX24 832 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 5),
    ('Samsung 198 L Direct Cool Single Door 4 Star Refrigerator (RR21T2H2XCR)', 'Samsung', 'Refrigerators', 30),
    ('Samsung 212 L Direct Cool Single Door 3 Star Refrigerator (RR22M272ZS8)', 'Samsung', 'Refrigerators', 25),
    ('Samsung 183 L Direct Cool Single Door 3 Star Refrigerator (RR20D1823RZ/HL)', 'Samsung', 'Refrigerators', 20),
    ('Samsung 363 L Frost Free Double Door 2 Star Refrigerator (RT39C5532BS/HL)', 'Samsung', 'Refrigerators', 15),
    ('Samsung 845 L Frost Free Side by Side Refrigerator (RS82A6000SL/TL)', 'Samsung', 'Refrigerators', 10),
    ('Samsung 192 L Direct Cool Single Door 3 Star Refrigerator (RR20A182YR2/HL)', 'Samsung', 'Refrigerators', 25),
    ('Samsung 324 L Frost Free Double Door 3 Star Refrigerator (RT34A4623S8/HL)', 'Samsung', 'Refrigerators', 20),
    ('Samsung 253 L Frost Free Double Door 3 Star Refrigerator (RT28A3453S8/HL)', 'Samsung', 'Refrigerators', 18),
    ('Samsung 314 L Frost Free Double Door 3 Star Refrigerator (RT34T4632SL/HL)', 'Samsung', 'Refrigerators', 16),
    ('Samsung 700 L Frost Free Side by Side Refrigerator (RS72A500FCL/TL)', 'Samsung', 'Refrigerators', 14),
    ('Samsung 253 L Frost Free Double Door 2 Star Refrigerator (RT28T3483S8/HL)', 'Samsung', 'Refrigerators', 13),
    ('Samsung 726 L Frost Free Double Door 4 Star Refrigerator (RT28T3C23UW/HL)', 'Samsung', 'Refrigerators', 12),
    ('Samsung 212 L Direct Cool Single Door 2 Star Refrigerator (RR22A2C2X7R/NL)', 'Samsung', 'Refrigerators', 10),
    ('Samsung 323 L Frost Free Double Door 3 Star Refrigerator (RT28T3923S9/HL)', 'Samsung', 'Refrigerators', 9),
    ('Samsung 198 L Direct Cool Single Door 3 Star Refrigerator (RR21T2C2XCR/NL)', 'Samsung', 'Refrigerators', 8),
    ('Samsung 478 L Frost Free Double Door 3 Star Refrigerator (RT50T5032S9/HL)', 'Samsung', 'Refrigerators', 7),
    ('Samsung 374 L Frost Free Double Door 3 Star Refrigerator (RT34T4513S9/HL)', 'Samsung', 'Refrigerators', 6),
    ('Samsung 514 L Frost Free Double Door 3 Star Refrigerator (RT28T3033S8/HL)', 'Samsung', 'Refrigerators', 5),
    ('Samsung 244 L Frost Free Double Door 2 Star Refrigerator (RT28A3032S8/HL)', 'Samsung', 'Refrigerators', 4),
    ('Samsung 219 L Direct Cool Single Door 2 Star Refrigerator (RR19T1Z2XUT/NL)', 'Samsung', 'Refrigerators', 3),
    ('LG 6.5 kg Fully-Automatic Top Loading Washing Machine (T65SNSF1Z, Blue and White)', 'LG', 'Washing Machines', 'Fully-Automatic', 'Top Loading', '6.5 kg', 30),
    ('LG 7 kg Fully-Automatic Top Loading Washing Machine (T70SJSF1Z, Middle Free Silver)', 'LG', 'Washing Machines', 'Fully-Automatic', 'Top Loading', '7 kg', 25),
    ('LG 8 kg Fully-Automatic Top Loading Washing Machine (T80SJBK1Z, Middle Black)', 'LG', 'Washing Machines', 'Fully-Automatic', 'Top Loading', '8 kg', 20),
    ('LG 6 kg Fully-Automatic Front Loading Washing Machine (FHT1006SNW, White)', 'LG', 'Washing Machines', 'Fully-Automatic', 'Front Loading', '6 kg', 18),
    ('LG 7 kg Fully-Automatic Front Loading Washing Machine (FHT1207ZNS, Stone Silver)', 'LG', 'Washing Machines', 'Fully-Automatic', 'Front Loading', '7 kg', 15),
    ('LG 8 kg Fully-Automatic Front Loading Washing Machine (FHT1408SWS, Silver)', 'LG', 'Washing Machines', 'Fully-Automatic', 'Front Loading', '8 kg', 14),
    ('LG 10.5 kg Fully-Automatic Front Loading Washing Machine (FHTD105SWS, White)', 'LG', 'Washing Machines', 'Fully-Automatic', 'Front Loading', '10.5 kg', 12),
    ('LG 7 kg Semi-Automatic Top Loading Washing Machine (P7020NGAY, Dark Gray)', 'LG', 'Washing Machines', 'Semi-Automatic', 'Top Loading', '7 kg', 10),
    ('LG 8 kg Semi-Automatic Top Loading Washing Machine (P8035SPMZ, Purple)', 'LG', 'Washing Machines', 'Semi-Automatic', 'Top Loading', '8 kg', 8),
    ('LG 6.5 kg Inverter Fully-Automatic Top Loading Washing Machine (T65SKSF4Z, Middle Free Silver)', 'LG', 'Washing Machines', 'Fully-Automatic', 'Top Loading', '6.5 kg', 6),
    ('LG 7.5 kg Inverter Fully-Automatic Top Loading Washing Machine (T75SKSF4Z, Free Silver)', 'LG', 'Washing Machines', 'Fully-Automatic', 'Top Loading', '7.5 kg', 5),
    ('LG 8.5 kg Inverter Fully-Automatic Top Loading Washing Machine (T85SKSF4Z, Free Silver)', 'LG', 'Washing Machines', 'Fully-Automatic', 'Top Loading', '8.5 kg', 4),
    ('LG 7.0 Kg 5 Star Inverter Fully-Automatic Front Loading Washing Machine (FHM1207ZDL, Luxury Silver)', 'LG', 'Washing Machines', 'Fully-Automatic', 'Front Loading', '7.0 kg', 3),
    ('LG 6.0 Kg 5 Star Inverter Fully-Automatic Front Loading Washing Machine (FHM1006ZNL, Luxury Silver)', 'LG', 'Washing Machines', 'Fully-Automatic', 'Front Loading', '6.0 kg', 2),
    ('LG 10.5 kg Fully-Automatic Front Loading Washing Machine (FHTD105WWB, White)', 'LG', 'Washing Machines', 'Fully-Automatic', 'Front Loading', '10.5 kg', 1),
    ('LG 6.5 Kg 5 Star Inverter Fully-Automatic Front Loading Washing Machine (FHM1065ZWS, White)', 'LG', 'Washing Machines', 'Fully-Automatic', 'Front Loading', '6.5 kg', 1),
    ('LG 7.5 Kg 5 Star Inverter Fully-Automatic Front Loading Washing Machine (FHM1275ZWS, White)', 'LG', 'Washing Machines', 'Fully-Automatic', 'Front Loading', '7.5 kg', 1),
    ('LG 8.5 Kg 5 Star Smart Inverter Fully-Automatic Top Loading Washing Machine (T85SNSL4Z, Middle Free Silver)', 'LG', 'Washing Machines', 'Fully-Automatic', 'Top Loading', '8.5 kg', 1),
    ('LG 9.5 Kg 5 Star Smart Inverter Fully-Automatic Top Loading Washing Machine (T95SNSL4Z, Middle Free Silver)', 'LG', 'Washing Machines', 'Fully-Automatic', 'Top Loading', '9.5 kg', 1),
    ('Samsung 6.5 kg Fully-Automatic Top Loading Washing Machine (WA65A4002VS/TL, Imperial Silver)', 'Samsung', 'Washing Machines', 'Fully-Automatic', 'Top Loading', '6.5 kg', 30),
    ('Samsung 7 kg Fully-Automatic Top Loading Washing Machine (WA70A4002GS/TL, Sparkling Grey)', 'Samsung', 'Washing Machines', 'Fully-Automatic', 'Top Loading', '7 kg', 25),
    ('Samsung 8 kg Fully-Automatic Top Loading Washing Machine (WA80A4002GS/TL, Sparkling Grey)', 'Samsung', 'Washing Machines', 'Fully-Automatic', 'Top Loading', '8 kg', 20),
    ('Samsung 6 kg Fully-Automatic Front Loading Washing Machine (WW60R20GLMA/TL, White)', 'Samsung', 'Washing Machines', 'Fully-Automatic', 'Front Loading', '6 kg', 18),
    ('Samsung 7 kg Fully-Automatic Front Loading Washing Machine (WW70J42G0KW/TL, White)', 'Samsung', 'Washing Machines', 'Fully-Automatic', 'Front Loading', '7 kg', 15),
    ('Samsung 8 kg Fully-Automatic Front Loading Washing Machine (WW80J4243MW/TL, White)', 'Samsung', 'Washing Machines', 'Fully-Automatic', 'Front Loading', '8 kg', 14),
    ('Samsung 10 kg Fully-Automatic Front Loading Washing Machine (WW10N64FRPW/TL, White)', 'Samsung', 'Washing Machines', 'Fully-Automatic', 'Front Loading', '10 kg', 12),
    ('Samsung 6.5 kg Semi-Automatic Top Loading Washing Machine (WT657QPNDPGXTL, White and Maroon)', 'Samsung', 'Washing Machines', 'Semi-Automatic', 'Top Loading', '6.5 kg', 10),
    ('Samsung 7.2 kg Semi-Automatic Top Loading Washing Machine (WT725QPNDMPXTL, White and Blue)', 'Samsung', 'Washing Machines', 'Semi-Automatic', 'Top Loading', '7.2 kg', 8),
    ('Samsung 8 kg Semi-Automatic Top Loading Washing Machine (WT80R4200LG/TL, Light Grey)', 'Samsung', 'Washing Machines', 'Semi-Automatic', 'Top Loading', '8 kg', 6),
    ('Samsung 6.5 kg Inverter Fully-Automatic Top Loading Washing Machine (WA65A4002VS/TL, Imperial Silver)', 'Samsung', 'Washing Machines', 'Fully-Automatic', 'Top Loading', '6.5 kg', 6),
    ('Samsung 7.5 kg Inverter Fully-Automatic Top Loading Washing Machine (WA75A4022FS/TL, Silver)', 'Samsung', 'Washing Machines', 'Fully-Automatic', 'Top Loading', '7.5 kg', 5),
    ('Samsung 8.5 kg Inverter Fully-Automatic Top Loading Washing Machine (WA85A4022NS/TL, Silver)', 'Samsung', 'Washing Machines', 'Fully-Automatic', 'Top Loading', '8.5 kg', 4),
    ('Samsung 7.0 kg 5 Star Inverter Fully-Automatic Front Loading Washing Machine (WW70T504DAW/TL, White)', 'Samsung', 'Washing Machines', 'Fully-Automatic', 'Front Loading', '7.0 kg', 3),
    ('Samsung 6.0 kg 5 Star Inverter Fully-Automatic Front Loading Washing Machine (WW60R20GLMA/TL, White)', 'Samsung', 'Washing Machines', 'Fully-Automatic', 'Front Loading', '6.0 kg', 2),
    ('Samsung 10.5 kg Fully-Automatic Front Loading Washing Machine (WW10N64FRPW/TL, White)', 'Samsung', 'Washing Machines', 'Fully-Automatic', 'Front Loading', '10.5 kg', 1),
    ('Samsung 6.5 kg 5 Star Inverter Fully-Automatic Front Loading Washing Machine (WW65R20GLSW/TL, White)', 'Samsung', 'Washing Machines', 'Fully-Automatic', 'Front Loading', '6.5 kg', 1),
    ('Samsung 7.5 kg 5 Star Inverter Fully-Automatic Front Loading Washing Machine (WW75R20GLSW/TL, White)', 'Samsung', 'Washing Machines', 'Fully-Automatic', 'Front Loading', '7.5 kg', 1),
    ('Samsung 8.5 kg 5 Star Inverter Fully-Automatic Front Loading Washing Machine (WW85R20GLSW/TL, White)', 'Samsung', 'Washing Machines', 'Fully-Automatic', 'Front Loading', '8.5 kg', 1),
    ('Samsung 9.5 kg 5 Star Inverter Fully-Automatic Front Loading Washing Machine (WW95R20GLSW/TL, White)', 'Samsung', 'Washing Machines', 'Fully-Automatic', 'Front Loading', '9.5 kg', 1),



]

# Connect to MySQL database
conn = pymysql.connect(host='localhost',
                       user='root',
                       password='root',
                       database='warehouse',
                       charset='utf8mb4',
                       cursorclass=pymysql.cursors.DictCursor)

try:
    with conn.cursor() as cursor:
        # Delete existing data from the table
        cursor.execute("DELETE FROM products")

        # Insert curated products to achieve 1000 products in total
        for i in range(700):
            product, brand, category, quantity = products[i % len(products)]
            warehouse = "Warehouse"
            product_id = f"{brand[:3].upper()}{category[:2].upper()}{i + 1}"
            cursor.execute("INSERT INTO products VALUES (%s, %s, %s, %s, %s, %s)",
                           (product_id, product, brand, category, warehouse, quantity))

    # Commit changes
    conn.commit()
    print("Data inserted successfully.")
finally:
    # Close connection
    conn.close()

