import pymysql

products = [
    ('boAt Airdopes 441', 'boAt', 'Earbuds', 300),
    ('boAt Rockerz 550', 'boAt', 'Headphones', 250),
    ('boAt Stone 200', 'boAt', 'Speakers', 200),
    ('boAt Rockerz 255', 'boAt', 'Headphones', 150),
    ('boAt Stone 170', 'boAt', 'Speakers', 10),
    ('boAt Bassheads 100', 'boAt', 'Earbuds', 500),
    ('boAt Airdopes 131', 'boAt', 'Earbuds', 250),
    ('boAt Rockerz 450', 'boAt', 'Headphones', 200),
    ('boAt Stone 260', 'boAt', 'Speakers', 200),
    ('boAt Rockerz 255 Pro+', 'boAt', 'Headphones', 100),
    ('boAt Stone 1200', 'boAt', 'Speakers', 500),
    ('boAt Airdopes 402', 'boAt', 'Earbuds', 200),
    ('boAt Rockerz 510', 'boAt', 'Headphones', 150),
    ('boAt Stone 1000', 'boAt', 'Speakers', 10),
    ('boAt Rockerz 600', 'boAt', 'Headphones', 500),
    ('boAt Airdopes 131v2', 'boAt', 'Earbuds', 200),
    ('boAt Rockerz 400', 'boAt', 'Headphones', 150),
    ('boAt Stone 650', 'boAt', 'Speakers', 10),
    ('boAt Rockerz 255F Pro', 'boAt', 'Headphones', 500),
    ('boAt Airdopes 621', 'boAt', 'Earbuds', 200),
    ('boAt Airdopes 621B', 'boAt', 'Earbuds', 250),
    ('boAt Rockerz 255 Pro', 'boAt', 'Headphones', 200),
    ('boAt Stone 200A', 'boAt', 'Speakers', 200),
    ('boAt Airdopes 441 Pro', 'boAt', 'Earbuds', 100),
    ('boAt Rockerz 330', 'boAt', 'Headphones', 500),
    ('JBL Flip 5', 'JBL', 'Speakers', 200),
    ('JBL Quantum 800', 'JBL', 'Headphones', 120),
    ('JBL Charge 5', 'JBL', 'Speakers', 900),
    ('JBL Quantum 800', 'JBL', 'Headphones', 120),
    ('JBL Flip 5', 'JBL', 'Speakers', 200),
    ('JBL Quantum 800', 'JBL', 'Headphones', 120),
    ('JBL Charge 5', 'JBL', 'Speakers', 900),
    ('JBL Quantum 800', 'JBL', 'Headphones', 120),
    ('JBL Flip 5', 'JBL', 'Speakers', 200),
    ('JBL Quantum 800', 'JBL', 'Headphones', 120),
    ('JBL Charge 5', 'JBL', 'Speakers', 900),
    ('JBL Quantum 800', 'JBL', 'Headphones', 120),
    ('JBL Flip 5', 'JBL', 'Speakers', 200),
    ('JBL Quantum 800', 'JBL', 'Headphones', 120),
    ('JBL Charge 5', 'JBL', 'Speakers', 900),
    ('JBL Quantum 800', 'JBL', 'Headphones', 120),
    ('JBL Flip 5', 'JBL', 'Speakers', 200),
    ('JBL Quantum 800', 'JBL', 'Headphones', 120),
    ('JBL Charge 5', 'JBL', 'Speakers', 900),
    ('JBL Quantum 800', 'JBL', 'Headphones', 120),
    ('JBL Flip 5', 'JBL', 'Speakers', 200),
    ('JBL Quantum 800', 'JBL', 'Headphones', 120),
    ('JBL Charge 5', 'JBL', 'Speakers', 900),
    ('JBL Quantum 800', 'JBL', 'Headphones', 120),
    ('JBL Flip 5', 'JBL', 'Speakers', 200),
    ('OnePlus Bullets Wireless Z', 'OnePlus', 'Neckband', 300),
    ('OnePlus Buds Z', 'OnePlus', 'Earphones', 250),
    ('OnePlus Bullets Wireless Z Bass Edition', 'OnePlus', 'Neckband', 200),
    ('OnePlus Buds', 'OnePlus', 'Earphones', 150),
    ('OnePlus Bullets Wireless', 'OnePlus', 'Neckband', 10),
    ('OnePlus Bullets Wireless Z2', 'OnePlus', 'Neckband', 500),
    ('OnePlus Buds Pro', 'OnePlus', 'Earphones', 250),
    ('OnePlus Buds Z2', 'OnePlus', 'Earphones', 200),
    ('OnePlus Buds Pro White', 'OnePlus', 'Earphones', 150),
    ('OnePlus Buds White', 'OnePlus', 'Earphones', 100),
    ('OnePlus Buds Pro Black', 'OnePlus', 'Earphones', 500),
    ('OnePlus Bullets Wireless Z Blue', 'OnePlus', 'Neckband', 200),
    ('OnePlus Bullets Wireless Z Black', 'OnePlus', 'Neckband', 200),
    ('OnePlus Bullets Wireless Z Bass Edition Black', 'OnePlus', 'Neckband', 10),
    ('OnePlus Bullets Wireless Z Bass Edition White', 'OnePlus', 'Neckband', 500),
    ('OnePlus Buds Z Black', 'OnePlus', 'Earphones', 200),
    ('OnePlus Buds Z White', 'OnePlus', 'Earphones', 150),
    ('OnePlus Buds Gray', 'OnePlus', 'Earphones', 100),
    ('OnePlus Buds Z2 Black', 'OnePlus', 'Earphones', 500),
    ('OnePlus Buds Z2 White', 'OnePlus', 'Earphones', 200),
    ('OnePlus Buds Pro Blue', 'OnePlus', 'Earphones', 150),
    ('OnePlus Buds Pro Black', 'OnePlus', 'Earphones', 100),
    ('OnePlus Buds Pro Glossy White', 'OnePlus', 'Earphones', 500),
    ('OnePlus Buds Pro Matte Black', 'OnePlus', 'Earphones', 200),
    ('OnePlus Buds Pro Matte White', 'OnePlus', 'Earphones', 150),
    ('Noise Tune Charge', 'Noise', 'Neckband', 300),
    ('Noise Tune Elite', 'Noise', 'Neckband', 250),
    ('Noise Tune Flex', 'Noise', 'Neckband', 200),
    ('Noise Tune Active', 'Noise', 'Neckband', 200),
    ('Noise Tune Sport 2', 'Noise', 'Neckband', 10),
    ('Noise Tune Sport Pro', 'Noise', 'Neckband', 500),
    ('Noise Shots X5 Pro', 'Noise', 'Earphones', 250),
    ('Noise Shots Rush', 'Noise', 'Earphones', 200),
    ('Noise Shots X1 AIR', 'Noise', 'Earphones', 150),
    ('Noise Shots XO', 'Noise', 'Earphones', 100),
    ('Noise Shots X3 BASS', 'Noise', 'Earphones', 500),
    ('Noise Air Buds Pro', 'Noise', 'Earphones', 250),
    ('Noise Air Buds Mini', 'Noise', 'Earphones', 200),
    ('Noise Air Buds', 'Noise', 'Earphones', 150),
    ('Noise Buds Play', 'Noise', 'Earphones', 100),
    ('Noise Buds Solo', 'Noise', 'Earphones', 500),
    ('Noise Flair 2.0', 'Noise', 'Headphones', 200),
    ('Noise Defy Plus', 'Noise', 'Headphones', 150),
    ('Noise Defy', 'Noise', 'Headphones', 100),
    ('Noise Tune LITE', 'Noise', 'Headphones', 500),
    ('Noise Barrel 2.0', 'Noise', 'Speakers', 200),
    ('Noise Vibe 2.0', 'Noise', 'Speakers', 200),
    ('Noise Aqua 2.0', 'Noise', 'Speakers', 10),
    ('Noise Buddy 2.0', 'Noise', 'Speakers', 500),
    ('Realme Buds Wireless 2', 'Realme', 'Neckband', 300),
    ('Realme Buds Wireless 2 Neo', 'Realme', 'Neckband', 250),
    ('Realme Buds Wireless', 'Realme', 'Neckband', 200),
    ('Realme Buds Air 2', 'Realme', 'Earphones', 150),
    ('Realme Buds Air Pro', 'Realme', 'Earphones', 100),
    ('Realme Buds Air Neo', 'Realme', 'Earphones', 500),
    ('Realme Buds Q2', 'Realme', 'Earphones', 250),
    ('Realme Buds Q', 'Realme', 'Earphones', 200),
    ('Realme Buds Classic', 'Realme', 'Earphones', 150),
    ('Realme Buds Wireless Pro', 'Realme', 'Earphones', 100),
    ('Realme Buds 2', 'Realme', 'Earphones', 500),
    ('Realme Buds Air 3', 'Realme', 'Earphones', 250),
    ('Realme Buds Air 2 Neo', 'Realme', 'Earphones', 200),
    ('Realme Buds Air', 'Realme', 'Earphones', 150),
    ('Realme Buds Air 2 Pro', 'Realme', 'Earphones', 100),
    ('Realme Buds Air Pro Master Edition', 'Realme', 'Earphones', 500),
    ('Realme Buds Wireless 3', 'Realme', 'Earphones', 250),
    ('Realme Buds Wireless 2 Pro', 'Realme', 'Earphones', 200),
    ('Realme Buds Q2 Neo', 'Realme', 'Earphones', 150),
    ('Realme Buds Wireless Pro Master Edition', 'Realme', 'Earphones', 100),
    ('Realme Buds Wireless 2 Pro Master Edition', 'Realme', 'Earphones', 500),
    ('Realme Buds Air Pro 2', 'Realme', 'Earphones', 250),
    ('Realme Buds Air 2 Neo Active', 'Realme', 'Earphones', 200),
    ('Realme Buds Air 2 Neo Bass Boost+', 'Realme', 'Earphones', 150),
    ('Realme Buds Air 2 Neo Bass Boost', 'Realme', 'Earphones', 100),
    ('Realme Buds Air 2 Neo Bass', 'Realme', 'Earphones', 500),
    ('Redmi SonicBass Wireless Earphones', 'Redmi', 'Earphones', 300),
    ('Redmi Earbuds 2C', 'Redmi', 'Earphones', 250),
    ('Redmi Earbuds S', 'Redmi', 'Earphones', 200),
    ('Redmi Hi-Resolution Audio Wired Earphones', 'Redmi', 'Earphones', 150),
    ('Redmi Earbuds 3 Pro', 'Redmi', 'Earphones', 100),
    ('Redmi Earbuds 3', 'Redmi', 'Earphones', 500),
    ('Redmi SonicBass Wireless Neckband Earphones', 'Redmi', 'Neckband', 250),
    ('Redmi Neckband Wireless Earphones', 'Redmi', 'Neckband', 200),
    ('Redmi Earbuds 3 TWS', 'Redmi', 'Earphones', 150),
    ('Redmi Earbuds 2C TWS', 'Redmi', 'Earphones', 100),
    ('Redmi Earbuds 2 TWS', 'Redmi', 'Earphones', 500),
    ('Redmi SonicBass Wireless Earphones 2', 'Redmi', 'Earphones', 300),
    ('Redmi Earbuds 3 Pro TWS', 'Redmi', 'Earphones', 250),
    ('Redmi Earbuds 3 TWS Pro', 'Redmi', 'Earphones', 200),
    ('Redmi Earbuds 3 Pro Max', 'Redmi', 'Earphones', 150),
    ('Redmi AirDots 3 Pro', 'Redmi', 'Earphones', 100),
    ('Redmi AirDots 3', 'Redmi', 'Earphones', 500),
    ('Redmi SonicBass Wireless Neckband Earphones 2', 'Redmi', 'Neckband', 250),
    ('Redmi Earbuds 3 Pro TWS Lite', 'Redmi', 'Earphones', 200),
    ('Redmi Earbuds 3 TWS Lite', 'Redmi', 'Earphones', 150),
    ('Redmi Earbuds 2C TWS Lite', 'Redmi', 'Earphones', 100),
    ('Redmi SonicBass Wireless Earphones 2 Pro', 'Redmi', 'Earphones', 500),
    ('Redmi AirDots 3 Pro Max', 'Redmi', 'Earphones', 300),
    ('Redmi Earbuds 3 Pro TWS Max', 'Redmi', 'Earphones', 250),
    ('Redmi Earbuds 3 TWS Pro Max', 'Redmi', 'Earphones', 200),
    ('Apple AirPods Max', 'Apple', 'Headphones', 300),
    ('Apple AirPods Pro', 'Apple', 'Earphones', 250),
    ('Apple AirPods (3rd generation)', 'Apple', 'Earphones', 200),
    ('Beats Studio Buds', 'Apple', 'Earphones', 150),
    ('Beats Flex', 'Apple', 'Earphones', 100),
    ('Beats Powerbeats Pro', 'Apple', 'Earphones', 500),
    ('Beats Solo Pro', 'Apple', 'Headphones', 205),
    ('Beats Solo3 Wireless', 'Apple', 'Headphones', 200),
    ('Beats EP', 'Apple', 'Headphones', 150),
    ('Beats Studio3 Wireless', 'Apple', 'Headphones', 100),
    ('Beats Pill+', 'Apple', 'Speakers', 250),
    ('Beats Pill XL', 'Apple', 'Speakers', 24),
    ('Beats Pill 2.0', 'Apple', 'Speakers', 23),
    ('Beats Pill Mini', 'Apple', 'Speakers', 21),
    ('Beats Pill Dude', 'Apple', 'Speakers', 200),
    ('Beats Pill Character', 'Apple', 'Speakers', 19),
    ('Beats Pill Sleeve', 'Apple', 'Speakers', 200),
    ('Beats Pill+ App', 'Apple', 'Speakers', 17),
    ('Beats Pill+ Stand', 'Apple', 'Speakers', 16),
    ('Beats Pill XL+', 'Apple', 'Speakers', 120),
    ('OnePlus Watch', 'OnePlus', 'Smartwatches', 300),
    ('OnePlus Watch Cobalt Limited Edition', 'OnePlus', 'Smartwatches', 250),
    ('OnePlus Watch Harry Potter Edition', 'OnePlus', 'Smartwatches', 200),
    ('OnePlus Watch Cyberpunk 2077 Edition', 'OnePlus', 'Smartwatches', 200),
    ('OnePlus Watch LX', 'OnePlus', 'Smartwatches', 10),
    ('OnePlus Watch Cobalt Limited Edition RWBY', 'OnePlus', 'Smartwatches', 500),
    ('Noise ColorFit Ultra', 'Noise', 'Smartwatches', 300),
    ('Noise ColorFit Pro 3', 'Noise', 'Smartwatches', 250),
    ('Noise ColorFit Pro 2', 'Noise', 'Smartwatches', 200),
    ('Noise ColorFit Pro', 'Noise', 'Smartwatches', 200),
    ('Noise ColorFit Nav', 'Noise', 'Smartwatches', 10),
    ('Noise ColorFit Pulse', 'Noise', 'Smartwatches', 500),
    ('boAt Xtend', 'boAt', 'Smartwatches', 300),
    ('boAt Watch Enigma', 'boAt', 'Smartwatches', 250),
    ('boAt Flash', 'boAt', 'Smartwatches', 200),
    ('boAt Xplorer', 'boAt', 'Smartwatches', 200),
    ('boAt Flash Pro', 'boAt', 'Smartwatches', 10),
    ('boAt Watch Storm', 'boAt', 'Smartwatches', 500),
    ('Apple Watch Series 7', 'Apple', 'Smartwatches', 300),
    ('Apple Watch SE', 'Apple', 'Smartwatches', 250),
    ('Apple Watch Series 6', 'Apple', 'Smartwatches', 200),
    ('Apple Watch Series 5', 'Apple', 'Smartwatches', 200),
    ('Apple Watch Series 4', 'Apple', 'Smartwatches', 10),
    ('Apple Watch Series 3', 'Apple', 'Smartwatches', 500),
    ('Fire-Boltt 360', 'Fire-Boltt', 'Smartwatches', 300),
    ('Fire-Boltt Ninja', 'Fire-Boltt', 'Smartwatches', 250),
    ('Fire-Boltt Beast', 'Fire-Boltt', 'Smartwatches', 200),
    ('Fire-Boltt Thunder', 'Fire-Boltt', 'Smartwatches', 200),
    ('Fire-Boltt Ring', 'Fire-Boltt', 'Smartwatches', 10),
    ('Fire-Boltt Fuel', 'Fire-Boltt', 'Smartwatches', 500),
    ('iPhone 13', 'Apple', 'Mobile Phones', 500),
    ('iPhone 13 Pro', 'Apple', 'Mobile Phones', 500),
    ('iPhone 13 Pro Max', 'Apple', 'Mobile Phones', 400),
    ('iPhone 12', 'Apple', 'Mobile Phones', 400),
    ('iPhone 12 Mini', 'Apple', 'Mobile Phones', 300),
    ('iPhone 12 Pro', 'Apple', 'Mobile Phones', 250),
    ('iPhone 12 Pro Max', 'Apple', 'Mobile Phones', 200),
    ('iPhone SE (2nd generation)', 'Apple', 'Mobile Phones', 200),
    ('iPhone 11', 'Apple', 'Mobile Phones', 10),
    ('iPhone 11 Pro', 'Apple', 'Mobile Phones', 500),
    ('iPhone 11 Pro Max', 'Apple', 'Mobile Phones', 500),
    ('iPhone XR', 'Apple', 'Mobile Phones', 500),
    ('iPhone XS', 'Apple', 'Mobile Phones', 400),
    ('iPhone XS Max', 'Apple', 'Mobile Phones', 400),
    ('iPhone X', 'Apple', 'Mobile Phones', 300),
    ('iPhone 8', 'Apple', 'Mobile Phones', 250),
    ('iPhone 8 Plus', 'Apple', 'Mobile Phones', 200),
    ('iPhone 7', 'Apple', 'Mobile Phones', 200),
    ('iPhone 7 Plus', 'Apple', 'Mobile Phones', 10),
    ('iPhone SE (1st generation)', 'Apple', 'Mobile Phones', 500),
    ('iPhone 6s', 'Apple', 'Mobile Phones', 500),
    ('iPhone 6s Plus', 'Apple', 'Mobile Phones', 500),
    ('iPhone 6', 'Apple', 'Mobile Phones', 400),
    ('iPhone 6 Plus', 'Apple', 'Mobile Phones', 400),
    ('iPhone 5s', 'Apple', 'Mobile Phones', 300),
    ('Samsung Galaxy S21 Ultra', 'Samsung', 'Mobile Phones', 500),
    ('Samsung Galaxy S21', 'Samsung', 'Mobile Phones', 500),
    ('Samsung Galaxy S21 Plus', 'Samsung', 'Mobile Phones', 400),
    ('Samsung Galaxy Note 20 Ultra', 'Samsung', 'Mobile Phones', 400),
    ('Samsung Galaxy Note 20', 'Samsung', 'Mobile Phones', 300),
    ('Samsung Galaxy S20 Ultra', 'Samsung', 'Mobile Phones', 250),
    ('Samsung Galaxy S20', 'Samsung', 'Mobile Phones', 200),
    ('Samsung Galaxy S20 Plus', 'Samsung', 'Mobile Phones', 200),
    ('Samsung Galaxy Z Fold 2', 'Samsung', 'Mobile Phones', 10),
    ('Samsung Galaxy Z Flip', 'Samsung', 'Mobile Phones', 500),
    ('Samsung Galaxy Z Flip 3', 'Samsung', 'Mobile Phones', 500),
    ('Samsung Galaxy Z Fold 3', 'Samsung', 'Mobile Phones', 500),
    ('Samsung Galaxy A72', 'Samsung', 'Mobile Phones', 400),
    ('Samsung Galaxy A52', 'Samsung', 'Mobile Phones', 400),
    ('Samsung Galaxy A32', 'Samsung', 'Mobile Phones', 300),
    ('Samsung Galaxy A12', 'Samsung', 'Mobile Phones', 250),
    ('Samsung Galaxy M51', 'Samsung', 'Mobile Phones', 200),
    ('Samsung Galaxy M31', 'Samsung', 'Mobile Phones', 200),
    ('Samsung Galaxy M21', 'Samsung', 'Mobile Phones', 10),
    ('Samsung Galaxy M11', 'Samsung', 'Mobile Phones', 500),
    ('Samsung Galaxy Tab S7', 'Samsung', 'Tablets', 400),
    ('Samsung Galaxy Tab S6 Lite', 'Samsung', 'Tablets', 400),
    ('Samsung Galaxy Tab A7', 'Samsung', 'Tablets', 300),
    ('Samsung Galaxy Tab S5e', 'Samsung', 'Tablets', 250),
    ('Samsung Galaxy Tab S7+', 'Samsung', 'Tablets', 200),
    ('Samsung Galaxy Tab S6', 'Samsung', 'Tablets', 200),
    ('Samsung Galaxy Tab S6 Lite', 'Samsung', 'Tablets', 10),
    ('Samsung Galaxy Tab A 10.1', 'Samsung', 'Tablets', 500),
    ('Samsung Galaxy Watch 4', 'Samsung', 'Smartwatches', 300),
    ('Samsung Galaxy Watch 4 Classic', 'Samsung', 'Smartwatches', 250),
    ('Samsung Galaxy Watch 3', 'Samsung', 'Smartwatches', 200),
    ('Samsung Galaxy Watch Active 2', 'Samsung', 'Smartwatches', 200),
    ('Samsung Galaxy Watch', 'Samsung', 'Smartwatches', 10),
    ('Samsung Galaxy Watch Active', 'Samsung', 'Smartwatches', 500),
    ('Samsung Galaxy Buds Pro', 'Samsung', 'Earbuds', 400),
    ('Samsung Galaxy Buds Live', 'Samsung', 'Earbuds', 305),
    ('Samsung Galaxy Buds+', 'Samsung', 'Earbuds', 300),
    ('Samsung Galaxy Buds', 'Samsung', 'Earbuds', 250),
    ('Samsung Galaxy Buds 2', 'Samsung', 'Earbuds', 200),
    ('Samsung Galaxy Buds Pro', 'Samsung', 'Earbuds', 150),
    ('Samsung Galaxy Buds Live', 'Samsung', 'Earbuds', 100),
    ('Samsung Galaxy Buds+', 'Samsung', 'Earbuds', 500),
    ('Samsung Galaxy Watch 4', 'Samsung', 'Smartwatches', 300),
    ('Samsung Galaxy Watch 4 Classic', 'Samsung', 'Smartwatches', 250),
    ('Samsung Galaxy Watch 3', 'Samsung', 'Smartwatches', 200),
    ('Samsung Galaxy Watch Active 2', 'Samsung', 'Smartwatches', 200),
    ('Samsung Galaxy Watch', 'Samsung', 'Smartwatches', 10),
    ('Samsung Galaxy Watch Active', 'Samsung', 'Smartwatches', 500),
    ('Samsung Galaxy Fit 2', 'Samsung', 'Fitness Bands', 400),
    ('Samsung Galaxy Fit', 'Samsung', 'Fitness Bands', 350),
    ('Samsung Galaxy Fit e', 'Samsung', 'Fitness Bands', 300),
    ('Samsung Galaxy Fit 2', 'Samsung', 'Fitness Bands', 205),
    ('Samsung Galaxy Fit', 'Samsung', 'Fitness Bands', 200),
    ('Samsung Galaxy Fit e', 'Samsung', 'Fitness Bands', 150),
    ('Samsung Galaxy Buds Fit', 'Samsung', 'Fitness Earbuds', 100),
    ('Samsung Galaxy Buds Fit', 'Samsung', 'Fitness Earbuds', 500),
    ('Vivo X70 Pro+', 'Vivo', 'Mobile Phones', 500),
    ('Vivo X70 Pro', 'Vivo', 'Mobile Phones', 500),
    ('Vivo X70', 'Vivo', 'Mobile Phones', 400),
    ('Vivo V21 5G', 'Vivo', 'Mobile Phones', 400),
    ('Vivo V21e', 'Vivo', 'Mobile Phones', 300),
    ('Vivo Y73s', 'Vivo', 'Mobile Phones', 250),
    ('Vivo Y72 5G', 'Vivo', 'Mobile Phones', 200),
    ('Vivo Y52s', 'Vivo', 'Mobile Phones', 200),
    ('Vivo Y51A', 'Vivo', 'Mobile Phones', 10),
    ('Vivo Y20A', 'Vivo', 'Mobile Phones', 500),
    ('Vivo T1 5G', 'Vivo', 'Mobile Phones', 500),
    ('Vivo S9 5G', 'Vivo', 'Mobile Phones', 500),
    ('Vivo Y76s 5G', 'Vivo', 'Mobile Phones', 400),
    ('Vivo Y54s 5G', 'Vivo', 'Mobile Phones', 400),
    ('Vivo X60 Pro+', 'Vivo', 'Mobile Phones', 300),
    ('Vivo X60 Pro', 'Vivo', 'Mobile Phones', 250),
    ('Vivo X60', 'Vivo', 'Mobile Phones', 200),
    ('Vivo V23 Pro 5G', 'Vivo', 'Mobile Phones', 200),
    ('Vivo V23e 5G', 'Vivo', 'Mobile Phones', 10),
    ('Vivo V23 5G', 'Vivo', 'Mobile Phones', 500),
    ('Vivo Y76 5G', 'Vivo', 'Mobile Phones', 500),
    ('Vivo Y72 5G', 'Vivo', 'Mobile Phones', 500),
    ('Vivo Y53s 5G', 'Vivo', 'Mobile Phones', 400),
    ('Vivo Y31s 5G', 'Vivo', 'Mobile Phones', 400),
    ('Vivo Y12s', 'Vivo', 'Mobile Phones', 300),
    ('Oppo Find X5 Pro', 'Oppo', 'Mobile Phones', 58),
    ('Oppo Reno7 Pro 5G', 'Oppo', 'Mobile Phones', 600),
    ('Oppo Reno7 5G', 'Oppo', 'Mobile Phones', 52),
    ('Oppo Reno6 Pro 5G', 'Oppo', 'Mobile Phones', 500),
    ('Oppo Reno6 5G', 'Oppo', 'Mobile Phones', 48),
    ('Oppo A95 5G', 'Oppo', 'Mobile Phones', 500),
    ('Oppo A74 5G', 'Oppo', 'Mobile Phones', 400),
    ('Oppo A56 5G', 'Oppo', 'Mobile Phones', 400),
    ('Oppo A16', 'Oppo', 'Mobile Phones', 300),
    ('Oppo A74', 'Oppo', 'Mobile Phones', 400),
    ('Oppo A54', 'Oppo', 'Mobile Phones', 33),
    ('Oppo A16s', 'Oppo', 'Mobile Phones', 300),
    ('Oppo A54s', 'Oppo', 'Mobile Phones', 28),
    ('Oppo A15', 'Oppo', 'Mobile Phones', 250),
    ('Oppo A16e', 'Oppo', 'Mobile Phones', 200),
    ('Oppo A16K', 'Oppo', 'Mobile Phones', 200),
    ('Oppo A74s', 'Oppo', 'Mobile Phones', 200),
    ('Oppo A16K Pro', 'Oppo', 'Mobile Phones', 200),
    ('Oppo A16K Core', 'Oppo', 'Mobile Phones', 120),
    ('Oppo F19 Pro+ 5G', 'Oppo', 'Mobile Phones', 500),
    ('Oppo F19 Pro', 'Oppo', 'Mobile Phones', 500),
    ('Oppo F19', 'Oppo', 'Mobile Phones', 400),
    ('Oppo F19s', 'Oppo', 'Mobile Phones', 400),
    ('Oppo F17 Pro', 'Oppo', 'Mobile Phones', 300),
    ('OnePlus 10 Pro', 'OnePlus', 'Mobile Phones', 52),
    ('OnePlus 9 Pro', 'OnePlus', 'Mobile Phones', 500),
    ('OnePlus 9', 'OnePlus', 'Mobile Phones', 400),
    ('OnePlus 9R', 'OnePlus', 'Mobile Phones', 400),
    ('OnePlus Nord 2', 'OnePlus', 'Mobile Phones', 300),
    ('OnePlus Nord CE 5G', 'OnePlus', 'Mobile Phones', 400),
    ('OnePlus Nord N200 5G', 'OnePlus', 'Mobile Phones', 33),
    ('OnePlus 8T', 'OnePlus', 'Mobile Phones', 300),
    ('OnePlus 8 Pro', 'OnePlus', 'Mobile Phones', 28),
    ('OnePlus 8', 'OnePlus', 'Mobile Phones', 250),
    ('OnePlus 8T+', 'OnePlus', 'Mobile Phones', 200),
    ('OnePlus 8T Pro', 'OnePlus', 'Mobile Phones', 200),
    ('OnePlus 7T Pro', 'OnePlus', 'Mobile Phones', 200),
    ('OnePlus 7T', 'OnePlus', 'Mobile Phones', 200),
    ('OnePlus 7 Pro', 'OnePlus', 'Mobile Phones', 120),
    ('OnePlus 7', 'OnePlus', 'Mobile Phones', 10),
    ('OnePlus 6T', 'OnePlus', 'Mobile Phones', 800),
    ('OnePlus 6', 'OnePlus', 'Mobile Phones', 500),
    ('OnePlus 5T', 'OnePlus', 'Mobile Phones', 120),
    ('OnePlus 5', 'OnePlus', 'Mobile Phones', 10),
    ('OnePlus 3T', 'OnePlus', 'Mobile Phones', 800),
    ('OnePlus 3', 'OnePlus', 'Mobile Phones', 500),
    ('OnePlus 2', 'OnePlus', 'Mobile Phones', 120),
    ('OnePlus One', 'OnePlus', 'Mobile Phones', 10),
    ('OnePlus X', 'OnePlus', 'Mobile Phones', 800),
    ('Realme GT 2 Pro', 'Realme', 'Mobile Phones', 47),
    ('Realme GT 2', 'Realme', 'Mobile Phones', 500),
    ('Realme GT Neo 3', 'Realme', 'Mobile Phones', 400),
    ('Realme GT Neo 2', 'Realme', 'Mobile Phones', 400),
    ('Realme GT Master Edition', 'Realme', 'Mobile Phones', 300),
    ('Realme 9 Pro+', 'Realme', 'Mobile Phones', 400),
    ('Realme 9 Pro', 'Realme', 'Mobile Phones', 33),
    ('Realme 9', 'Realme', 'Mobile Phones', 300),
    ('Realme 9i', 'Realme', 'Mobile Phones', 28),
    ('Realme 8 Pro', 'Realme', 'Mobile Phones', 250),
    ('Realme 8', 'Realme', 'Mobile Phones', 200),
    ('Realme 8i', 'Realme', 'Mobile Phones', 200),
    ('Realme 8s', 'Realme', 'Mobile Phones', 200),
    ('Realme 7 Pro', 'Realme', 'Mobile Phones', 200),
    ('Realme 7', 'Realme', 'Mobile Phones', 120),
    ('Realme 7i', 'Realme', 'Mobile Phones', 10),
    ('Realme 7s', 'Realme', 'Mobile Phones', 800),
    ('Realme 6 Pro', 'Realme', 'Mobile Phones', 250),
    ('Realme 6', 'Realme', 'Mobile Phones', 200),
    ('Realme 6i', 'Realme', 'Mobile Phones', 200),
    ('Realme 6s', 'Realme', 'Mobile Phones', 200),
    ('Realme 5 Pro', 'Realme', 'Mobile Phones', 200),
    ('Realme 5', 'Realme', 'Mobile Phones', 120),
    ('Realme 5s', 'Realme', 'Mobile Phones', 10),
    ('Redmi Note 11 Pro', 'Redmi', 'Mobile Phones', 48),
    ('Redmi Note 11', 'Redmi', 'Mobile Phones', 500),
    ('Redmi Note 11S', 'Redmi', 'Mobile Phones', 400),
    ('Redmi Note 11T', 'Redmi', 'Mobile Phones', 400),
    ('Redmi Note 11 4G', 'Redmi', 'Mobile Phones', 300),
    ('Redmi Note 11 Pro+', 'Redmi', 'Mobile Phones', 400),
    ('Redmi Note 11 5G', 'Redmi', 'Mobile Phones', 33),
    ('Redmi 10', 'Redmi', 'Mobile Phones', 300),
    ('Redmi 10 Prime', 'Redmi', 'Mobile Phones', 28),
    ('Redmi 10A', 'Redmi', 'Mobile Phones', 250),
    ('Redmi 9T', 'Redmi', 'Mobile Phones', 200),
    ('Redmi 9 Power', 'Redmi', 'Mobile Phones', 200),
    ('Redmi 9A', 'Redmi', 'Mobile Phones', 200),
    ('Redmi 9C', 'Redmi', 'Mobile Phones', 200),
    ('Redmi Note 10 Pro', 'Redmi', 'Mobile Phones', 120),
    ('Redmi Note 10', 'Redmi', 'Mobile Phones', 10),
    ('Redmi Note 10S', 'Redmi', 'Mobile Phones', 800),
    ('Redmi Note 10 5G', 'Redmi', 'Mobile Phones', 250),
    ('Redmi K40 Gaming Edition', 'Redmi', 'Mobile Phones', 200),
    ('Redmi K40', 'Redmi', 'Mobile Phones', 200),
    ('Redmi K40 Pro', 'Redmi', 'Mobile Phones', 200),
    ('Redmi K40 Pro+', 'Redmi', 'Mobile Phones', 200),
    ('Redmi K30 Ultra', 'Redmi', 'Mobile Phones', 120),
    ('Redmi K30S Ultra', 'Redmi', 'Mobile Phones', 10),
    ('Nokia G50', 'Nokia', 'Mobile Phones', 400),
    ('Nokia G21', 'Nokia', 'Mobile Phones', 400),
    ('Nokia G10', 'Nokia', 'Mobile Phones', 300),
    ('Nokia G20', 'Nokia', 'Mobile Phones', 400),
    ('Nokia XR20', 'Nokia', 'Mobile Phones', 33),
    ('Nokia 5.4', 'Nokia', 'Mobile Phones', 300),
    ('Nokia 3.4', 'Nokia', 'Mobile Phones', 28),
    ('Nokia 2.4', 'Nokia', 'Mobile Phones', 250),
    ('Nokia 8.3 5G', 'Nokia', 'Mobile Phones', 200),
    ('Nokia 5.3', 'Nokia', 'Mobile Phones', 200),
    ('Nokia 7.2', 'Nokia', 'Mobile Phones', 200),
    ('Nokia 6.2', 'Nokia', 'Mobile Phones', 200),
    ('Nokia 9 PureView', 'Nokia', 'Mobile Phones', 120),
    ('Nokia 8.1', 'Nokia', 'Mobile Phones', 10),
    ('Nokia 7 Plus', 'Nokia', 'Mobile Phones', 800),
    ('Nokia 6.1', 'Nokia', 'Mobile Phones', 250),
    ('Nokia 5.1', 'Nokia', 'Mobile Phones', 200),
    ('Nokia 3.1', 'Nokia', 'Mobile Phones', 200),
    ('Nokia 2.1', 'Nokia', 'Mobile Phones', 200),
    ('Nokia 1.4', 'Nokia', 'Mobile Phones', 200),
    ('Nokia 1 Plus', 'Nokia', 'Mobile Phones', 120),
    ('Nokia 8 Sirocco', 'Nokia', 'Mobile Phones', 10),
    ('Nokia 7.1', 'Nokia', 'Mobile Phones', 800),
    ('Nokia 6.1 Plus', 'Nokia', 'Mobile Phones', 250),
    ('Nokia 5.1 Plus', 'Nokia', 'Mobile Phones', 200),
    ('Motorola Edge 20', 'Motorola', 'Mobile Phones', 400),
    ('Motorola Edge 20 Pro', 'Motorola', 'Mobile Phones', 400),
    ('Motorola Edge 20 Lite', 'Motorola', 'Mobile Phones', 300),
    ('Motorola Moto G Pure', 'Motorola', 'Mobile Phones', 400),
    ('Motorola Moto G Power (2021)', 'Motorola', 'Mobile Phones', 33),
    ('Motorola Moto G Stylus (2021)', 'Motorola', 'Mobile Phones', 300),
    ('Motorola Moto G30', 'Motorola', 'Mobile Phones', 28),
    ('Motorola Moto G10', 'Motorola', 'Mobile Phones', 250),
    ('Motorola Moto G9 Power', 'Motorola', 'Mobile Phones', 200),
    ('Motorola Moto G9 Play', 'Motorola', 'Mobile Phones', 200),
    ('Motorola Moto G9 Plus', 'Motorola', 'Mobile Phones', 200),
    ('Motorola Moto G8 Power', 'Motorola', 'Mobile Phones', 200),
    ('Motorola Moto G8 Plus', 'Motorola', 'Mobile Phones', 120),
    ('Motorola Moto G8', 'Motorola', 'Mobile Phones', 10),
    ('Motorola Moto G7 Power', 'Motorola', 'Mobile Phones', 800),
    ('Motorola Moto G7 Play', 'Motorola', 'Mobile Phones', 250),
    ('Motorola Moto G7 Plus', 'Motorola', 'Mobile Phones', 200),
    ('Motorola Moto G7', 'Motorola', 'Mobile Phones', 200),
    ('Motorola Moto G6 Plus', 'Motorola', 'Mobile Phones', 200),
    ('Motorola Moto G6', 'Motorola', 'Mobile Phones', 200),
    ('Motorola Moto G6 Play', 'Motorola', 'Mobile Phones', 120),
    ('Motorola Moto G5S Plus', 'Motorola', 'Mobile Phones', 10),
    ('Motorola Moto G5S', 'Motorola', 'Mobile Phones', 800),
    ('Motorola Moto G5 Plus', 'Motorola', 'Mobile Phones', 250),
    ('Motorola Moto G5', 'Motorola', 'Mobile Phones', 200),
    ('Panasonic CS/CU-NU09VKYW 0.8 Ton 3 Star Inverter Split AC', 'Panasonic', 'Air Conditioners', 300),
    ('Panasonic CS/CU-NU12VKYW 1 Ton 4 Star Inverter Split AC', 'Panasonic', 'Air Conditioners', 250),
    ('Panasonic CS/CU-NU18VKYW 1.5 Ton 4 Star Inverter Split AC', 'Panasonic', 'Air Conditioners', 200),
    ('Panasonic CS/CU-NU24VKYW 2 Ton 4 Star Inverter Split AC', 'Panasonic', 'Air Conditioners', 150),
    ('Panasonic CS/CU-NU12VKYW 1 Ton 5 Star Inverter Split AC', 'Panasonic', 'Air Conditioners', 100),
    ('Panasonic CS/CU-NU18VKYW 1.5 Ton 5 Star Inverter Split AC', 'Panasonic', 'Air Conditioners', 500),
    ('Panasonic CS/CU-NU24VKYW 2 Ton 5 Star Inverter Split AC', 'Panasonic', 'Air Conditioners', 300),
    ('Panasonic CS/CU-NU09XKYW 0.8 Ton 3 Star Split AC', 'Panasonic', 'Air Conditioners', 250),
    ('Panasonic CS/CU-NU12XKYW 1 Ton 3 Star Split AC', 'Panasonic', 'Air Conditioners', 200),
    ('Panasonic CS/CU-NU18XKYW 1.5 Ton 3 Star Split AC', 'Panasonic', 'Air Conditioners', 150),
    ('Panasonic CS/CU-NU24XKYW 2 Ton 3 Star Split AC', 'Panasonic', 'Air Conditioners', 100),
    ('Panasonic CS/CU-NU09YKYW 0.8 Ton 5 Star Split AC', 'Panasonic', 'Air Conditioners', 500),
    ('Panasonic CS/CU-NU12YKYW 1 Ton 5 Star Split AC', 'Panasonic', 'Air Conditioners', 300),
    ('Panasonic CS/CU-NU18YKYW 1.5 Ton 5 Star Split AC', 'Panasonic', 'Air Conditioners', 250),
    ('Panasonic CS/CU-NU24YKYW 2 Ton 5 Star Split AC', 'Panasonic', 'Air Conditioners', 200),
    ('Panasonic CS/CU-SU09VKYW 0.8 Ton 3 Star Split AC', 'Panasonic', 'Air Conditioners', 150),
    ('Panasonic CS/CU-SU12VKYW 1 Ton 3 Star Split AC', 'Panasonic', 'Air Conditioners', 100),
    ('Panasonic CS/CU-SU18VKYW 1.5 Ton 3 Star Split AC', 'Panasonic', 'Air Conditioners', 500),
    ('Panasonic CS/CU-SU24VKYW 2 Ton 3 Star Split AC', 'Panasonic', 'Air Conditioners', 300),
    ('Panasonic CS/CU-SU09XKYW 0.8 Ton 4 Star Split AC', 'Panasonic', 'Air Conditioners', 250),
    ('Panasonic CS/CU-SU12XKYW 1 Ton 4 Star Split AC', 'Panasonic', 'Air Conditioners', 200),
    ('Panasonic CS/CU-SU18XKYW 1.5 Ton 4 Star Split AC', 'Panasonic', 'Air Conditioners', 150),
    ('Panasonic CS/CU-SU24XKYW 2 Ton 4 Star Split AC', 'Panasonic', 'Air Conditioners', 100),
    ('Panasonic CS/CU-SU09YKYW 0.8 Ton 5 Star Split AC', 'Panasonic', 'Air Conditioners', 500),
    ('Godrej GIC 12HTC5-WTA 1 Ton 5 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 300),
    ('Godrej GIC 18SOTC3-WTA 1.5 Ton 3 Star Split AC', 'Godrej', 'Air Conditioners', 250),
    ('Godrej GIC 24RTC3-WSA 2 Ton 3 Star Split AC', 'Godrej', 'Air Conditioners', 200),
    ('Godrej GIC 18YTC3-WTA 1.5 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 150),
    ('Godrej GIC 12FTC3-WSA 1 Ton 3 Star Split AC', 'Godrej', 'Air Conditioners', 100),
    ('Godrej GIC 12RTC3-WSA 1 Ton 3 Star Split AC', 'Godrej', 'Air Conditioners', 500),
    ('Godrej GIC 18WTC3-WTA 1.5 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 300),
    ('Godrej GIC 24BTB3-WRA 2 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 250),
    ('Godrej GIC 12NTC3-WTA 1 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 200),
    ('Godrej GIC 18LTC3-WSA 1.5 Ton 3 Star Split AC', 'Godrej', 'Air Conditioners', 150),
    ('Godrej GIC 24GTC3-WTA 2 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 100),
    ('Godrej GIC 18WTC3-WTA 1.5 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 500),
    ('Godrej GIC 12GTC3-WSA 1 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 300),
    ('Godrej GIC 24DTB3-WRA 2 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 250),
    ('Godrej GIC 18STC3-WTA 1.5 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 200),
    ('Godrej GIC 12FTC3-WTA 1 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 150),
    ('Godrej GIC 12FTC3-WTA 1 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 100),
    ('Godrej GIC 18FTC3-WSA 1.5 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 500),
    ('Godrej GIC 24FTC3-WSA 2 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 300),
    ('Godrej GIC 18OTC3-WSA 1.5 Ton 3 Star Inverter Split AC', 'Godrej', 'Air Conditioners', 250),
    ('LG KS-Q12YNZA 1 Ton 5 Star Inverter Split AC', 'LG', 'Air Conditioners', 300),
    ('LG KS-Q18YNZA 1.5 Ton 5 Star Inverter Split AC', 'LG', 'Air Conditioners', 250),
    ('LG KS-Q24YNXA 2 Ton 5 Star Inverter Split AC', 'LG', 'Air Conditioners', 200),
    ('LG KS-Q12HNZD 1 Ton 5 Star Hot and Cold Inverter Split AC', 'LG', 'Air Conditioners', 150),
    ('LG KS-Q18HNZD 1.5 Ton 5 Star Hot and Cold Inverter Split AC', 'LG', 'Air Conditioners', 100),
    ('LG KS-Q24ENXA 2 Ton 5 Star Inverter Split AC', 'LG', 'Air Conditioners', 500),
    ('LG MS-Q18YNZA 1.5 Ton 3 Star Inverter Split AC', 'LG', 'Air Conditioners', 300),
    ('LG MS-Q12YNZA 1 Ton 3 Star Inverter Split AC', 'LG', 'Air Conditioners', 250),
    ('LG KS-Q18GWZD 1.5 Ton 5 Star Inverter Split AC', 'LG', 'Air Conditioners', 200),
    ('LG KS-Q24GWZD 2 Ton 5 Star Inverter Split AC', 'LG', 'Air Conditioners', 150),
    ('LG KS-Q18HNXD 1.5 Ton 3 Star Hot and Cold Inverter Split AC', 'LG', 'Air Conditioners', 100),
    ('LG KS-Q12YNXA 1 Ton 5 Star Inverter Split AC', 'LG', 'Air Conditioners', 500),
    ('LG MS-Q18KNZA 1.5 Ton 3 Star Inverter Split AC', 'LG', 'Air Conditioners', 300),
    ('LG MS-Q12KNZA 1 Ton 3 Star Inverter Split AC', 'LG', 'Air Conditioners', 250),
    ('LG KS-Q18ENZA 1.5 Ton 5 Star Inverter Split AC', 'LG', 'Air Conditioners', 200),
    ('LG KS-Q12GWZD 1 Ton 5 Star Inverter Split AC', 'LG', 'Air Conditioners', 150),
    ('LG KS-Q12AWZD 1 Ton 5 Star Inverter Split AC', 'LG', 'Air Conditioners', 100),
    ('LG KS-Q18YNXA 1.5 Ton 5 Star Inverter Split AC', 'LG', 'Air Conditioners', 500),
    ('LG KS-Q24FNXD 2 Ton 3 Star Hot and Cold Inverter Split AC', 'LG', 'Air Conditioners', 300),
    ('Samsung AR18AYLYATNNA 1.5 Ton 5 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 300),
    ('Samsung AR18TV3JFMCNNA 1.5 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 250),
    ('Samsung AR18TY3QBBUNNA 1.5 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 200),
    ('Samsung AR12AYLYATNNA 1 Ton 5 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 150),
    ('Samsung AR18TY3QCBUNNA 1.5 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 100),
    ('Samsung AR18TY3QBBUNNA 1.5 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 500),
    ('Samsung AR24AYLYATNNA 2 Ton 5 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 300),
    ('Samsung AR18TY3QCBUNNA 1.5 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 250),
    ('Samsung AR18TV3HFTZNA 1.5 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 200),
    ('Samsung AR12TY3QBBUNNA 1 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 150),
    ('Samsung AR12TV3HFTZNA 1 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 100),
    ('Samsung AR18TY3QBBUNNA 1.5 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 500),
    ('Samsung AR18AYLYATNNA 1.5 Ton 5 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 300),
    ('Samsung AR18TV3JFMCNNA 1.5 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 205),
    ('Samsung AR18TY3QBBUNNA 1.5 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 200),
    ('Samsung AR12AYLYATNNA 1 Ton 5 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 150),
    ('Samsung AR18TY3QCBUNNA 1.5 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 100),
    ('Samsung AR18TY3QBBUNNA 1.5 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 500),
    ('Samsung AR24AYLYATNNA 2 Ton 5 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 300),
    ('Samsung AR18TY3QCBUNNA 1.5 Ton 3 Star Inverter Split AC', 'Samsung', 'Air Conditioners', 250),
    ('Panasonic TH-43HX635DX 43 inch UHD Smart LED TV', 'Panasonic', 'Televisions', 300),
    ('Panasonic TH-32HS625DX 32 inch HD Ready Smart LED TV', 'Panasonic', 'Televisions', 250),
    ('Panasonic TH-58HX450DX 58 inch Ultra HD 4K Smart LED TV', 'Panasonic', 'Televisions', 200),
    ('Panasonic TH-43HX635DX 43 inch UHD Smart LED TV', 'Panasonic', 'Televisions', 150),
    ('Panasonic TH-40HS450DX 40 inch Full HD Smart LED TV', 'Panasonic', 'Televisions', 100),
    ('Panasonic TH-43HS655DX 43 inch Full HD Smart LED TV', 'Panasonic', 'Televisions', 500),
    ('Panasonic TH-50HX635DX 50 inch UHD Smart LED TV', 'Panasonic', 'Televisions', 300),
    ('Panasonic TH-32JS660DX 32 inch HD Ready Smart LED TV', 'Panasonic', 'Televisions', 250),
    ('Panasonic TH-43HS700DX 43 inch Full HD Smart LED TV', 'Panasonic', 'Televisions', 200),
    ('Panasonic TH-43HS700DX 43 inch Full HD Smart LED TV', 'Panasonic', 'Televisions', 200),
    ('Panasonic TH-32JS660DX 32 inch HD Ready Smart LED TV', 'Panasonic', 'Televisions', 10),
    ('Panasonic TH-32JS660DX 32 inch HD Ready Smart LED TV', 'Panasonic', 'Televisions', 500),
    ('Panasonic TH-43HX635DX 43 inch UHD Smart LED TV', 'Panasonic', 'Televisions', 300),
    ('Panasonic TH-32HS625DX 32 inch HD Ready Smart LED TV', 'Panasonic', 'Televisions', 250),
    ('Panasonic TH-58HX450DX 58 inch Ultra HD 4K Smart LED TV', 'Panasonic', 'Televisions', 200),
    ('Panasonic TH-43HX635DX 43 inch UHD Smart LED TV', 'Panasonic', 'Televisions', 200),
    ('Panasonic TH-40HS450DX 40 inch Full HD Smart LED TV', 'Panasonic', 'Televisions', 10),
    ('Panasonic TH-43HS655DX 43 inch Full HD Smart LED TV', 'Panasonic', 'Televisions', 500),
    ('Panasonic TH-50HX635DX 50 inch UHD Smart LED TV', 'Panasonic', 'Televisions', 300),
    ('Panasonic TH-32JS660DX 32 inch HD Ready Smart LED TV', 'Panasonic', 'Televisions', 250),
    ('LG 43UM7290PTF 43 inch Ultra HD 4K LED Smart TV', 'LG', 'Televisions', 300),
    ('LG 32LM636BPTB 32 inch HD Ready LED Smart TV', 'LG', 'Televisions', 250),
    ('LG 55UM7290PTD 55 inch Ultra HD 4K LED Smart TV', 'LG', 'Televisions', 200),
    ('LG 43LM5650PTA 43 inch Full HD LED Smart TV', 'LG', 'Televisions', 200),
    ('LG 32LM563BPTC 32 inch HD Ready LED Smart TV', 'LG', 'Televisions', 10),
    ('LG 43UM7290PTF 43 inch Ultra HD 4K LED Smart TV', 'LG', 'Televisions', 500),
    ('LG 50UN7300PTC 50 inch Ultra HD 4K LED Smart TV', 'LG', 'Televisions', 300),
    ('LG 32LM636BPTB 32 inch HD Ready LED Smart TV', 'LG', 'Televisions', 250),
    ('LG 55UM7290PTD 55 inch Ultra HD 4K LED Smart TV', 'LG', 'Televisions', 200),
    ('LG 43LM5650PTA 43 inch Full HD LED Smart TV', 'LG', 'Televisions', 200),
    ('LG 32LM563BPTC 32 inch HD Ready LED Smart TV', 'LG', 'Televisions', 10),
    ('LG 43UM7290PTF 43 inch Ultra HD 4K LED Smart TV', 'LG', 'Televisions', 500),
    ('LG 50UN7300PTC 50 inch Ultra HD 4K LED Smart TV', 'LG', 'Televisions', 300),
    ('LG 32LM636BPTB 32 inch HD Ready LED Smart TV', 'LG', 'Televisions', 250),
    ('LG 55UM7290PTD 55 inch Ultra HD 4K LED Smart TV', 'LG', 'Televisions', 200),
    ('LG 43LM5650PTA 43 inch Full HD LED Smart TV', 'LG', 'Televisions', 200),
    ('LG 32LM563BPTC 32 inch HD Ready LED Smart TV', 'LG', 'Televisions', 10),
    ('LG 43UM7290PTF 43 inch Ultra HD 4K LED Smart TV', 'LG', 'Televisions', 500),
    ('LG 50UN7300PTC 50 inch Ultra HD 4K LED Smart TV', 'LG', 'Televisions', 300),
    ('Samsung UA32T4340AKXXL 32 inch HD Ready LED TV', 'Samsung', 'Televisions', 300),
    ('Samsung UA43T5470AKXXL 43 inch Ultra HD 4K Smart LED TV', 'Samsung', 'Televisions', 250),
    ('Samsung UA50TUE60AKXXL 50 inch Ultra HD 4K LED TV', 'Samsung', 'Televisions', 200),
    ('Samsung UA55TU8000KXXL 55 inch Ultra HD 4K LED Smart TV', 'Samsung', 'Televisions', 200),
    ('Samsung UA43T5350AKXXL 43 inch Full HD LED Smart TV', 'Samsung', 'Televisions', 10),
    ('Samsung UA32T4300DKXXL 32 inch HD Ready LED TV', 'Samsung', 'Televisions', 500),
    ('Samsung UA43T5470AKXXL 43 inch Ultra HD 4K Smart LED TV', 'Samsung', 'Televisions', 300),
    ('Samsung UA50TUE60AKXXL 50 inch Ultra HD 4K LED TV', 'Samsung', 'Televisions', 250),
    ('Samsung UA55TU8000KXXL 55 inch Ultra HD 4K LED Smart TV', 'Samsung', 'Televisions', 200),
    ('Samsung UA43T5350AKXXL 43 inch Full HD LED Smart TV', 'Samsung', 'Televisions', 200),
    ('Samsung UA32T4300DKXXL 32 inch HD Ready LED TV', 'Samsung', 'Televisions', 10),
    ('Samsung UA43T5470AKXXL 43 inch Ultra HD 4K Smart LED TV', 'Samsung', 'Televisions', 500),
    ('Samsung UA50TUE60AKXXL 50 inch Ultra HD 4K LED TV', 'Samsung', 'Televisions', 300),
    ('Samsung UA55TU8000KXXL 55 inch Ultra HD 4K LED Smart TV', 'Samsung', 'Televisions', 250),
    ('Samsung UA43T5350AKXXL 43 inch Full HD LED Smart TV', 'Samsung', 'Televisions', 200),
    ('Samsung UA32T4300DKXXL 32 inch HD Ready LED TV', 'Samsung', 'Televisions', 200),
    ('Samsung UA43T5470AKXXL 43 inch Ultra HD 4K Smart LED TV', 'Samsung', 'Televisions', 100),
    ('Samsung UA50TUE60AKXXL 50 inch Ultra HD 4K LED TV', 'Samsung', 'Televisions', 500),
    ('Samsung UA55TU8000KXXL 55 inch Ultra HD 4K LED Smart TV', 'Samsung', 'Televisions', 300),
    ('HP Pavilion 15-eg0103TX 15.6 inch FHD Laptop', 'HP', 'Laptops', 300),
    ('HP Pavilion x360 14-dh1178TU 14 inch FHD Touchscreen Laptop', 'HP', 'Laptops', 250),
    ('HP 15s-du3047TX 15.6 inch FHD Laptop', 'HP', 'Laptops', 200),
    ('HP Pavilion Gaming 15-dk0261TX 15.6 inch FHD Laptop', 'HP', 'Laptops', 150),
    ('HP Envy x360 Convertible 13-ay0078AU 13.3 inch FHD Touchscreen Laptop', 'HP', 'Laptops', 100),
    ('HP Omen 15-ek0019TX 15.6 inch FHD Gaming Laptop', 'HP', 'Laptops', 500),
    ('HP Pavilion 15-eg0103TX 15.6 inch FHD Laptop', 'HP', 'Laptops', 300),
    ('HP Pavilion x360 14-dh1178TU 14 inch FHD Touchscreen Laptop', 'HP', 'Laptops', 250),
    ('HP 15s-du3047TX 15.6 inch FHD Laptop', 'HP', 'Laptops', 200),
    ('HP Pavilion Gaming 15-dk0261TX 15.6 inch FHD Laptop', 'HP', 'Laptops', 150),
    ('HP Envy x360 Convertible 13-ay0078AU 13.3 inch FHD Touchscreen Laptop', 'HP', 'Laptops', 100),
    ('HP Omen 15-ek0019TX 15.6 inch FHD Gaming Laptop', 'HP', 'Laptops', 500),
    ('HP Pavilion 15-eg0103TX 15.6 inch FHD Laptop', 'HP', 'Laptops', 300),
    ('HP Pavilion x360 14-dh1178TU 14 inch FHD Touchscreen Laptop', 'HP', 'Laptops', 250),
    ('HP 15s-du3047TX 15.6 inch FHD Laptop', 'HP', 'Laptops', 200),
    ('HP Pavilion Gaming 15-dk0261TX 15.6 inch FHD Laptop', 'HP', 'Laptops', 150),
    ('HP Envy x360 Convertible 13-ay0078AU 13.3 inch FHD Touchscreen Laptop', 'HP', 'Laptops', 100),
    ('HP Omen 15-ek0019TX 15.6 inch FHD Gaming Laptop', 'HP', 'Laptops', 500),
    ('HP Pavilion 15-eg0103TX 15.6 inch FHD Laptop', 'HP', 'Laptops', 300),
    ('HP Pavilion x360 14-dh1178TU 14 inch FHD Touchscreen Laptop', 'HP', 'Laptops', 250),
    ('HP Envy 15-ep0142TX 15.6 inch 4K UHD Laptop', 'HP', 'Laptops', 300),
    ('HP Spectre x360 13-aw0053TU 13.3 inch 4K UHD Touchscreen Laptop', 'HP', 'Laptops', 250),
    ('HP Pavilion Gaming 16-a0055TX 16.1 inch FHD Gaming Laptop', 'HP', 'Laptops', 200),
    ('HP Spectre x360 14-ea0064TU 13.5 inch 3K2K Touchscreen Laptop', 'HP', 'Laptops', 150),
    ('HP Omen 17-cb0079TX 17.3 inch FHD Gaming Laptop', 'HP', 'Laptops', 100),
    ('Dell XPS 13 9310 13.4 inch FHD+ Touchscreen Laptop', 'Dell', 'Laptops', 300),
    ('Dell Inspiron 5406 14 inch FHD Touchscreen 2in1 Laptop', 'Dell', 'Laptops', 250),
    ('Dell G3 3500 15.6 inch FHD Gaming Laptop', 'Dell', 'Laptops', 200),
    ('Dell XPS 15 9500 15.6 inch UHD+ Touchscreen Laptop', 'Dell', 'Laptops', 150),
    ('Dell Inspiron 7501 15.6 inch FHD Laptop', 'Dell', 'Laptops', 100),
    ('Dell Alienware m15 R4 15.6 inch FHD Gaming Laptop', 'Dell', 'Laptops', 500),
    ('Dell Latitude 3410 14 inch HD Laptop', 'Dell', 'Laptops', 300),
    ('Dell Precision 3551 15.6 inch FHD Mobile Workstation Laptop', 'Dell', 'Laptops', 250),
    ('Dell Vostro 3400 14 inch FHD Laptop', 'Dell', 'Laptops', 200),
    ('Dell Inspiron 3501 15.6 inch HD Laptop', 'Dell', 'Laptops', 150),
    ('Dell Latitude 5420 14 inch FHD Laptop', 'Dell', 'Laptops', 100),
    ('Dell XPS 17 9700 17 inch UHD+ Touchscreen Laptop', 'Dell', 'Laptops', 500),
    ('Dell Inspiron 3593 15.6 inch FHD Laptop', 'Dell', 'Laptops', 300),
    ('Dell Precision 5550 15.6 inch UHD+ Mobile Workstation Laptop', 'Dell', 'Laptops', 250),
    ('Dell Alienware m17 R4 17.3 inch FHD Gaming Laptop', 'Dell', 'Laptops', 200),
    ('Dell Inspiron 5402 14 inch FHD Laptop', 'Dell', 'Laptops', 150),
    ('Dell Latitude 7420 14 inch FHD Laptop', 'Dell', 'Laptops', 100),
    ('Dell Vostro 3500 15.6 inch FHD Laptop', 'Dell', 'Laptops', 500),
    ('Dell Inspiron 5505 15.6 inch FHD Laptop', 'Dell', 'Laptops', 300),
    ('Dell Precision 7550 15.6 inch UHD+ Mobile Workstation Laptop', 'Dell', 'Laptops', 250),
    ('Dell XPS 13 9305 13.3 inch FHD+ Laptop', 'Dell', 'Laptops', 200),
    ('Dell Alienware Area-51m R2 17.3 inch FHD Gaming Laptop', 'Dell', 'Laptops', 150),
    ('Dell Inspiron 3593 15.6 inch HD Laptop', 'Dell', 'Laptops', 100),
    ('Dell Latitude 5401 14 inch FHD Laptop', 'Dell', 'Laptops', 500),
    ('Dell G5 15 5500 15.6 inch FHD Gaming Laptop', 'Dell', 'Laptops', 300),
    ('LG GL-I292RPZL 260 L 4 Star Double Door Refrigerator', 'LG', 'Refrigerators', 300),
    ('LG GL-D201ARGY 190 L 4 Star Single Door Refrigerator', 'LG', 'Refrigerators', 250),
    ('LG GL-Q292SDSY 260 L 2 Star Double Door Refrigerator', 'LG', 'Refrigerators', 200),
    ('LG GL-T292SRGY 260 L 3 Star Double Door Refrigerator', 'LG', 'Refrigerators', 200),
    ('LG GL-C292SPZU 260 L 2 Star Double Door Refrigerator', 'LG', 'Refrigerators', 100),
    ('LG GL-E201ASRY 190 L 4 Star Single Door Refrigerator', 'LG', 'Refrigerators', 500),
    ('LG GL-I292RPZY 260 L 4 Star Double Door Refrigerator', 'LG', 'Refrigerators', 300),
    ('LG GL-D201APZY 190 L 4 Star Single Door Refrigerator', 'LG', 'Refrigerators', 250),
    ('LG GL-Q292SDSY 260 L 2 Star Double Door Refrigerator', 'LG', 'Refrigerators', 200),
    ('LG GL-T292SRGY 260 L 3 Star Double Door Refrigerator', 'LG', 'Refrigerators', 200),
    ('LG GL-C292SPZU 260 L 2 Star Double Door Refrigerator', 'LG', 'Refrigerators', 100),
    ('LG GL-E201ASRY 190 L 4 Star Single Door Refrigerator', 'LG', 'Refrigerators', 500),
    ('LG GL-I292RPZY 260 L 4 Star Double Door Refrigerator', 'LG', 'Refrigerators', 300),
    ('LG GL-D201APZY 190 L 4 Star Single Door Refrigerator', 'LG', 'Refrigerators', 250),
    ('LG GL-Q292SDSY 260 L 2 Star Double Door Refrigerator', 'LG', 'Refrigerators', 200),
    ('LG GL-T292SRGY 260 L 3 Star Double Door Refrigerator', 'LG', 'Refrigerators', 200),
    ('LG GL-C292SPZU 260 L 2 Star Double Door Refrigerator', 'LG', 'Refrigerators', 100),
    ('LG GL-E201ASRY 190 L 4 Star Single Door Refrigerator', 'LG', 'Refrigerators', 500),
    ('LG GL-I292RPZY 260 L 4 Star Double Door Refrigerator', 'LG', 'Refrigerators', 300),
    ('LG GL-D201APZY 190 L 4 Star Single Door Refrigerator', 'LG', 'Refrigerators', 250),
    ('LG GL-Q292SDSY 260 L 2 Star Double Door Refrigerator', 'LG', 'Refrigerators', 200),
    ('LG GL-T292SRGY 260 L 3 Star Double Door Refrigerator', 'LG', 'Refrigerators', 200),
    ('LG GL-C292SPZU 260 L 2 Star Double Door Refrigerator', 'LG', 'Refrigerators', 100),
    ('LG GL-E201ASRY 190 L 4 Star Single Door Refrigerator', 'LG', 'Refrigerators', 500),
    ('LG GL-I292RPZY 260 L 4 Star Double Door Refrigerator', 'LG', 'Refrigerators', 300),
    ('Panasonic NR-BL349VSX1 342 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 300),
    ('Panasonic NR-BL459VSX2 432 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 250),
    ('Panasonic NR-BL569VSX3 532 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 200),
    ('Panasonic NR-BL689VSX4 632 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 200),
    ('Panasonic NR-BL799VSX5 732 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 100),
    ('Panasonic NR-BL899VSX6 832 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 500),
    ('Panasonic NR-BL349VSX7 342 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 300),
    ('Panasonic NR-BL459VSX8 432 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 250),
    ('Panasonic NR-BL569VSX9 532 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 200),
    ('Panasonic NR-BL689VSX10 632 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 200),
    ('Panasonic NR-BL799VSX11 732 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 100),
    ('Panasonic NR-BL899VSX12 832 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 500),
    ('Panasonic NR-BL349VSX13 342 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 300),
    ('Panasonic NR-BL459VSX14 432 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 250),
    ('Panasonic NR-BL569VSX15 532 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 200),
    ('Panasonic NR-BL689VSX16 632 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 200),
    ('Panasonic NR-BL799VSX17 732 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 100),
    ('Panasonic NR-BL899VSX18 832 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 500),
    ('Panasonic NR-BL349VSX19 342 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 300),
    ('Panasonic NR-BL459VSX20 432 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 250),
    ('Panasonic NR-BL569VSX21 532 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 200),
    ('Panasonic NR-BL689VSX22 632 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 200),
    ('Panasonic NR-BL799VSX23 732 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 100),
    ('Panasonic NR-BL899VSX24 832 L 3 Star Double Door Refrigerator', 'Panasonic', 'Refrigerators', 500),
    ('Samsung 198 L Direct Cool Single Door 4 Star Refrigerator (RR21T2H2XCR)', 'Samsung', 'Refrigerators', 300),
    ('Samsung 212 L Direct Cool Single Door 3 Star Refrigerator (RR22M272ZS8)', 'Samsung', 'Refrigerators', 250),
    ('Samsung 183 L Direct Cool Single Door 3 Star Refrigerator (RR20D1823RZ/HL)', 'Samsung', 'Refrigerators', 200),
    ('Samsung 363 L Frost Free Double Door 2 Star Refrigerator (RT39C5532BS/HL)', 'Samsung', 'Refrigerators', 200),
    ('Samsung 845 L Frost Free Side by Side Refrigerator (RS82A6000SL/TL)', 'Samsung', 'Refrigerators', 100),
    ('Samsung 192 L Direct Cool Single Door 3 Star Refrigerator (RR20A182YR2/HL)', 'Samsung', 'Refrigerators', 250),
    ('Samsung 324 L Frost Free Double Door 3 Star Refrigerator (RT34A4623S8/HL)', 'Samsung', 'Refrigerators', 200),
    ('Samsung 253 L Frost Free Double Door 3 Star Refrigerator (RT28A3453S8/HL)', 'Samsung', 'Refrigerators', 200),
    ('Samsung 314 L Frost Free Double Door 3 Star Refrigerator (RT34T4632SL/HL)', 'Samsung', 'Refrigerators', 160),
    ('Samsung 700 L Frost Free Side by Side Refrigerator (RS72A500FCL/TL)', 'Samsung', 'Refrigerators', 200),
    ('Samsung 253 L Frost Free Double Door 2 Star Refrigerator (RT28T3483S8/HL)', 'Samsung', 'Refrigerators', 130),
    ('Samsung 726 L Frost Free Double Door 4 Star Refrigerator (RT28T3C23UW/HL)', 'Samsung', 'Refrigerators', 120),
    ('Samsung 212 L Direct Cool Single Door 2 Star Refrigerator (RR22A2C2X7R/NL)', 'Samsung', 'Refrigerators', 100),
    ('Samsung 323 L Frost Free Double Door 3 Star Refrigerator (RT28T3923S9/HL)', 'Samsung', 'Refrigerators', 900),
    ('Samsung 198 L Direct Cool Single Door 3 Star Refrigerator (RR21T2C2XCR/NL)', 'Samsung', 'Refrigerators', 800),
    ('Samsung 478 L Frost Free Double Door 3 Star Refrigerator (RT50T5032S9/HL)', 'Samsung', 'Refrigerators', 700),
    ('Samsung 374 L Frost Free Double Door 3 Star Refrigerator (RT34T4513S9/HL)', 'Samsung', 'Refrigerators', 600),
    ('Samsung 514 L Frost Free Double Door 3 Star Refrigerator (RT28T3033S8/HL)', 'Samsung', 'Refrigerators', 500),
    ('Samsung 244 L Frost Free Double Door 2 Star Refrigerator (RT28A3032S8/HL)', 'Samsung', 'Refrigerators', 200),
    ('Samsung 219 L Direct Cool Single Door 2 Star Refrigerator (RR19T1Z2XUT/NL)', 'Samsung', 'Refrigerators', 300),
    ('LG 6.5 kg Fully-Automatic Top Loading Washing Machine (T65SNSF1Z, Blue and White)', 'LG', 'Washing Machines', 300),
    ('LG 7 kg Fully-Automatic Top Loading Washing Machine (T70SJSF1Z, Middle Free Silver)', 'LG', 'Washing Machines', 250),
    ('LG 8 kg Fully-Automatic Top Loading Washing Machine (T80SJBK1Z, Middle Black)', 'LG', 'Washing Machines', 200),
    ('LG 6 kg Fully-Automatic Front Loading Washing Machine (FHT1006SNW, White)', 'LG', 'Washing Machines', 200),
    ('LG 7 kg Fully-Automatic Front Loading Washing Machine (FHT1207ZNS, Stone Silver)', 'LG', 'Washing Machines', 200),
    ('LG 8 kg Fully-Automatic Front Loading Washing Machine (FHT1408SWS, Silver)', 'LG', 'Washing Machines', 200),
    ('LG 10.5 kg Fully-Automatic Front Loading Washing Machine (FHTD105SWS, White)', 'LG', 'Washing Machines', 120),
    ('LG 7 kg Semi-Automatic Top Loading Washing Machine (P7020NGAY, Dark Gray)', 'LG', 'Washing Machines', 100),
    ('LG 8 kg Semi-Automatic Top Loading Washing Machine (P8035SPMZ, Purple)', 'LG', 'Washing Machines', 800),
    ('LG 6.5 kg Inverter Fully-Automatic Top Loading Washing Machine (T65SKSF4Z, Middle Free Silver)', 'LG', 'Washing Machines', 600),
    ('LG 7.5 kg Inverter Fully-Automatic Top Loading Washing Machine (T75SKSF4Z, Free Silver)', 'LG', 'Washing Machines', 500),
    ('LG 8.5 kg Inverter Fully-Automatic Top Loading Washing Machine (T85SKSF4Z, Free Silver)', 'LG', 'Washing Machines', 200),
    ('LG 7.0 Kg 5 Star Inverter Fully-Automatic Front Loading Washing Machine (FHM1207ZDL, Luxury Silver)', 'LG', 'Washing Machines', 300),
    ('LG 6.0 Kg 5 Star Inverter Fully-Automatic Front Loading Washing Machine (FHM1006ZNL, Luxury Silver)', 'LG', 'Washing Machines', 200),
    ('LG 10.5 kg Fully-Automatic Front Loading Washing Machine (FHTD105WWB, White)', 'LG', 'Washing Machines', 100),
    ('LG 6.5 Kg 5 Star Inverter Fully-Automatic Front Loading Washing Machine (FHM1065ZWS, White)', 'LG', 'Washing Machines', 100),
    ('LG 7.5 Kg 5 Star Inverter Fully-Automatic Front Loading Washing Machine (FHM1275ZWS, White)', 'LG', 'Washing Machines', 100),
    ('LG 8.5 Kg 5 Star Smart Inverter Fully-Automatic Top Loading Washing Machine (T85SNSL4Z, Middle Free Silver)', 'LG', 'Washing Machines', 100),
    ('LG 9.5 Kg 5 Star Smart Inverter Fully-Automatic Top Loading Washing Machine (T95SNSL4Z, Middle Free Silver)', 'LG', 'Washing Machines',100),
    ('Samsung 6.5 kg Fully-Automatic Top Loading Washing Machine (WA65A4002VS/TL, Imperial Silver)', 'Samsung', 'Washing Machines', 300),
    ('Samsung 7 kg Fully-Automatic Top Loading Washing Machine (WA70A4002GS/TL, Sparkling Grey)', 'Samsung', 'Washing Machines', 250),
    ('Samsung 8 kg Fully-Automatic Top Loading Washing Machine (WA80A4002GS/TL, Sparkling Grey)', 'Samsung', 'Washing Machines', 200),
    ('Samsung 6 kg Fully-Automatic Front Loading Washing Machine (WW60R20GLMA/TL, White)', 'Samsung', 'Washing Machines', 200),
    ('Samsung 7 kg Fully-Automatic Front Loading Washing Machine (WW70J42G0KW/TL, White)', 'Samsung', 'Washing Machines', 200),
    ('Samsung 8 kg Fully-Automatic Front Loading Washing Machine (WW80J4243MW/TL, White)', 'Samsung', 'Washing Machines', 200),
    ('Samsung 10 kg Fully-Automatic Front Loading Washing Machine (WW10N64FRPW/TL, White)', 'Samsung', 'Washing Machines', 120),
    ('Samsung 6.5 kg Semi-Automatic Top Loading Washing Machine (WT657QPNDPGXTL, White and Maroon)', 'Samsung', 'Washing Machines', 100),
    ('Samsung 7.2 kg Semi-Automatic Top Loading Washing Machine (WT725QPNDMPXTL, White and Blue)', 'Samsung', 'Washing Machines', 800),
    ('Samsung 8 kg Semi-Automatic Top Loading Washing Machine (WT80R4200LG/TL, Light Grey)', 'Samsung', 'Washing Machines', 600),
    ('Samsung 6.5 kg Inverter Fully-Automatic Top Loading Washing Machine (WA65A4002VS/TL, Imperial Silver)', 'Samsung', 'Washing Machines', 600),
    ('Samsung 7.5 kg Inverter Fully-Automatic Top Loading Washing Machine (WA75A4022FS/TL, Silver)', 'Samsung', 'Washing Machines', 500),
    ('Samsung 8.5 kg Inverter Fully-Automatic Top Loading Washing Machine (WA85A4022NS/TL, Silver)', 'Samsung', 'Washing Machines', 200),
    ('Samsung 7.0 kg 5 Star Inverter Fully-Automatic Front Loading Washing Machine (WW70T504DAW/TL, White)', 'Samsung', 'Washing Machines', 300),
    ('Samsung 6.0 kg 5 Star Inverter Fully-Automatic Front Loading Washing Machine (WW60R20GLMA/TL, White)', 'Samsung', 'Washing Machines', 200),
    ('Samsung 10.5 kg Fully-Automatic Front Loading Washing Machine (WW10N64FRPW/TL, White)', 'Samsung', 'Washing Machines',100),
    ('Samsung 6.5 kg 5 Star Inverter Fully-Automatic Front Loading Washing Machine (WW65R20GLSW/TL, White)', 'Samsung', 'Washing Machines', 100),
    ('Samsung 7.5 kg 5 Star Inverter Fully-Automatic Front Loading Washing Machine (WW75R20GLSW/TL, White)', 'Samsung', 'Washing Machines', 100),
    ('Samsung 8.5 kg 5 Star Inverter Fully-Automatic Front Loading Washing Machine (WW85R20GLSW/TL, White)', 'Samsung', 'Washing Machines', 100),
    ('Samsung 9.5 kg 5 Star Inverter Fully-Automatic Front Loading Washing Machine (WW95R20GLSW/TL, White)', 'Samsung', 'Washing Machines', 100),
    ('Redmi X2000 20000mAh Power Bank', 'Redmi', 'Accessories', 200),
    ('Redmi Y3000 20000mAh Power Bank', 'Redmi', 'Accessories', 300),
    ('Redmi Z4000 20000mAh Power Bank', 'Redmi', 'Accessories', 400),
    ('Redmi A5000 20000mAh Power Bank', 'Redmi', 'Accessories', 400),
    ('Redmi B6000 20000mAh Power Bank', 'Redmi', 'Accessories', 500),
    ('Redmi C7000 20000mAh Power Bank', 'Redmi', 'Accessories', 500),
    ('Redmi D8000 20000mAh Power Bank', 'Redmi', 'Accessories', 600),
    ('Redmi E9000 20000mAh Power Bank', 'Redmi', 'Accessories', 600),
    ('Redmi F10000 20000mAh Power Bank', 'Redmi', 'Accessories', 600),
    ('Redmi G11000 20000mAh Power Bank', 'Redmi', 'Accessories', 700),
    ('OnePlus X2000 10000mAh Power Bank', 'OnePlus', 'Accessories', 200),
    ('OnePlus Y3000 10000mAh Power Bank', 'OnePlus', 'Accessories', 240),
    ('OnePlus Z4000 10000mAh Power Bank', 'OnePlus', 'Accessories', 260),
    ('OnePlus A5000 10000mAh Power Bank', 'OnePlus', 'Accessories', 280),
    ('OnePlus B6000 10000mAh Power Bank', 'OnePlus', 'Accessories', 300),
    ('OnePlus C7000 10000mAh Power Bank', 'OnePlus', 'Accessories', 320),
    ('OnePlus D8000 10000mAh Power Bank', 'OnePlus', 'Accessories', 400),
    ('OnePlus E9000 10000mAh Power Bank', 'OnePlus', 'Accessories', 400),
    ('OnePlus F10000 10000mAh Power Bank', 'OnePlus', 'Accessories', 300),
    ('OnePlus G11000 10000mAh Power Bank', 'OnePlus', 'Accessories', 400),
    ('Redmi 20000mAh Power Bank', 'Redmi', 'Accessories', 250),
    ('Redmi 10000mAh Power Bank', 'Redmi', 'Accessories', 250),
    ('OnePlus P102A: 10000 mAh Power Bank', 'OnePlus', 'Accessories', 250),
    ('OnePlus 02030002: 10000 mAh Power Bank', 'OnePlus', 'Accessories', 250),
    ('Realme 10000mAh Power Bank 2', 'Realme', 'Accessories', 250),
    ('Realme Power Bank 3 PD 10000 mAh', 'Realme', 'Accessories', 300),
    ('Realme Power Bank 4i 10000 mAh', 'Realme', 'Accessories', 400),
    ('Realme Power Bank 5 Pro 10000 mAh', 'Realme', 'Accessories', 400),
    ('Realme Power Bank 6 Ultra 10000 mAh', 'Realme', 'Accessories', 500),
    ('Realme Power Bank 7 Fast Charge 10000 mAh', 'Realme', 'Accessories', 500),
    ('Realme Power Bank 8 SuperCharge 10000 mAh', 'Realme', 'Accessories', 600),
    ('Realme Power Bank 9 UltraFast 10000 mAh', 'Realme', 'Accessories', 600),
    ('Realme Power Bank 10 Extreme 10000 mAh', 'Realme', 'Accessories', 600),
    ('Redmi 27W SonicCharge Charger', 'Redmi', 'Accessories', 300),
    ('Redmi 18W Fast Charger', 'Redmi', 'Accessories', 400),
    ('Redmi 33W Power Adapter', 'Redmi', 'Accessories', 400),
    ('Redmi 45W SuperCharge Charger', 'Redmi', 'Accessories', 500),
    ('Samsung 25W Super Fast Charger', 'Samsung', 'Accessories', 500),
    ('Samsung 45W USB-C Fast Charging Wall Charger', 'Samsung', 'Accessories', 600),
    ('Samsung 65W Super Fast Charger', 'Samsung', 'Accessories', 600),
    ('OnePlus Warp Charge 30T Charger', 'OnePlus', 'Accessories', 600),
    ('OnePlus Warp Charge 65 Power Adapter', 'OnePlus', 'Accessories', 700),
    ('OnePlus Dash Charge 30W Power Adapter', 'OnePlus', 'Accessories', 800),
    ('Realme 65W SuperDart Charger', 'Realme', 'Accessories', 800),
    ('Realme 50W SuperVOOC Charger', 'Realme', 'Accessories', 800),
    ('Realme 30W Dart Charge Adapter', 'Realme', 'Accessories', 900),
    ('Realme 18W Quick Charger', 'Realme', 'Accessories', 900),
    ('Redmi USB Type-C Cable', 'Redmi', 'Accessories', 300),
    ('Redmi Micro USB Cable', 'Redmi', 'Accessories', 400),
    ('Samsung USB Type-C Cable', 'Samsung', 'Accessories', 400),
    ('Samsung Micro USB Cable', 'Samsung', 'Accessories', 500),
    ('OnePlus USB Type-C Cable', 'OnePlus', 'Accessories', 500),
    ('OnePlus Warp Charge Cable', 'OnePlus', 'Accessories', 600),
    ('Realme USB Type-C Cable', 'Realme', 'Accessories', 600),
    ('Realme Micro USB Cable', 'Realme', 'Accessories', 600),
    ('Redmi Tempered Glass (Gorilla Protection)', 'Redmi', 'Accessories', 300),
    ('Samsung Tempered Glass (UV Protection)', 'Samsung', 'Accessories', 400),
    ('OnePlus Tempered Glass (Gorilla Protection)', 'OnePlus', 'Accessories', 400),
    ('Realme Tempered Glass (UV Protection)', 'Realme', 'Accessories', 500),
    ('Redmi Silicone Mobile Cover', 'Redmi', 'Accessories', 200),
    ('Samsung Leather Mobile Cover', 'Samsung', 'Accessories', 250),
    ('OnePlus Hard Plastic Mobile Cover', 'OnePlus', 'Accessories', 300),
    ('Realme Transparent Mobile Cover', 'Realme', 'Accessories', 400),
    ('Redmi Shockproof Mobile Cover', 'Redmi', 'Accessories', 250),
    ('Samsung Flip Mobile Cover', 'Samsung', 'Accessories', 300),
    ('OnePlus Carbon Fiber Mobile Cover', 'OnePlus', 'Accessories', 400),
    ('Realme Printed Mobile Cover', 'Realme', 'Accessories', 400),
    ('Redmi Metal Bumper Mobile Cover', 'Redmi', 'Accessories', 300),
    ('Samsung Glitter Mobile Cover', 'Samsung', 'Accessories', 400),
    ('Redmi Camera Lens Protector', 'Redmi', 'Accessories', 200),
    ('Samsung Camera Lens Protector', 'Samsung', 'Accessories', 250),
    ('OnePlus Camera Lens Protector', 'OnePlus', 'Accessories', 300),
    ('Realme Camera Lens Protector', 'Realme', 'Accessories', 400),
    ('Redmi Scratch-resistant Lens Protector', 'Redmi', 'Accessories', 250),
    ('Samsung Anti-fingerprint Lens Protector', 'Samsung', 'Accessories', 300),
    ('OnePlus Ultra-thin Lens Protector', 'OnePlus', 'Accessories', 400),
    ('Realme HD Clear Lens Protector', 'Realme', 'Accessories', 400),
    ('Redmi Tempered Glass Lens Protector', 'Redmi', 'Accessories', 300),
    ('Samsung Nano-coated Lens Protector', 'Samsung', 'Accessories', 400),
    ('Logitech G305 LIGHTSPEED', 'Logitech', 'Accessories', 250),
    ('Logitech G502 X', 'Logitech',  'Accessories', 300),
    ('Logitech G Pro Wireless', 'Logitech',  'Accessories', 400),
    ('Logitech MX Master 3', 'Logitech',  'Accessories', 500),
    ('Logitech G903 LIGHTSPEED', 'Logitech',  'Accessories', 400),
    ('Logitech G402 Hyperion Fury', 'Logitech',  'Accessories', 400),
    ('Logitech MX Anywhere 3', 'Logitech',  'Accessories', 500),
    ('Logitech G502 HERO', 'Logitech',  'Accessories', 400),
    ('Logitech G703 LIGHTSPEED', 'Logitech',  'Accessories', 300),
    ('Logitech G600 MMO Gaming Mouse', 'Logitech',  'Accessories', 500),
    ('Logitech MX Vertical', 'Logitech',  'Accessories', 400),
    ('OnePlus Precision Wired Mouse', 'OnePlus', 'Accessories', 200),
    ('OnePlus Wireless Office Mouse', 'OnePlus', 'Accessories', 28),
    ('Redmi RGB Gaming Mouse', 'Redmi', 'Accessories', 250),
    ('Redmi Silent Click Wireless Mouse', 'Redmi', 'Accessories', 300),
    ('OnePlus High DPI Gaming Mouse', 'OnePlus', 'Accessories', 300),
    ('OnePlus Wireless Travel Mouse', 'OnePlus', 'Accessories', 400),
    ('Redmi Optical Wired Mouse', 'Redmi', 'Accessories', 200),
    ('Redmi Compact Wireless Mouse', 'Redmi', 'Accessories', 250),
    ('OnePlus High DPI Gaming Mouse', 'OnePlus', 'Accessories', 300),
    ('OnePlus Wireless Travel Mouse', 'OnePlus', 'Accessories', 400),
    ('Redmi Optical Wired Mouse', 'Redmi', 'Accessories', 200),
    ('Redmi Compact Wireless Mouse', 'Redmi', 'Accessories', 250),
    ('Logitech G305 LIGHTSPEED', 'Logitech', 'Accessories', 300),
    ('Logitech G502 X', 'Logitech', 'Accessories', 250),
    ('Logitech MX Master 3', 'Logitech', 'Accessories', 200),
    ('Logitech G Pro Wireless', 'Logitech', 'Accessories', 400),
    ('Logitech MX Anywhere 3', 'Logitech', 'Accessories', 300),
    ('Logitech Z407 Bluetooth Computer Speakers with Subwoofer', 'Logitech', 'Speakers', 200),
    ('Logitech Z623 400 Watt Home Speaker System', 'Logitech', 'Speakers', 10),
    ('Logitech Z906 5.1 Surround Sound Speaker System', 'Logitech', 'Speakers', 500),
    ('Logitech G560 LIGHTSYNC PC Gaming Speakers', 'Logitech', 'Speakers', 800),
    ('Logitech Z313 Speaker System', 'Logitech', 'Speakers', 120),
    ('Logitech Z533 Multimedia Speaker System', 'Logitech', 'Speakers', 200),
    ('Logitech Z623 THX Certified Speaker System', 'Logitech', 'Speakers', 200),
    ('Logitech Z337 Bold Sound Bluetooth Wireless 2.1 Speaker System', 'Logitech', 'Speakers', 200),
    ('Logitech Z207 2.0 Multi Device Stereo Speaker', 'Logitech', 'Speakers', 250),
    ('Logitech Z323 Speaker System', 'Logitech', 'Speakers', 300),
    ('Logitech Portable Microphone', 'Logitech', 'Accessories', 250),
    ('Logitech C920 HD Pro Webcam', 'Logitech', 'Accessories', 200),
    ('Logitech C922 Pro Stream Webcam', 'Logitech', 'Accessories', 200),
    ('Logitech BRIO Ultra HD Webcam', 'Logitech', 'Accessories', 200),
    ('Logitech C270 Desktop or Laptop Webcam', 'Logitech', 'Accessories', 200),
    ('Logitech C615 HD Webcam', 'Logitech', 'Accessories', 250),
    ('Logitech C310 HD Webcam', 'Logitech', 'Accessories', 200),
    ('Logitech C925e Webcam', 'Logitech', 'Accessories', 200),
    ('Logitech C930e 1080P HD Video Webcam', 'Logitech', 'Accessories', 200),
    ('Logitech C505 HD Webcam', 'Logitech', 'Accessories', 200),
    ('Logitech C920S HD Pro Webcam', 'Logitech', 'Accessories', 200),
    ('Logitech C922x Pro Stream Webcam', 'Logitech', 'Accessories', 200),
    ('Logitech StreamCam, 1080P HD 60fps Streaming Webcam', 'Logitech', 'Accessories', 200),
    ('Logitech C525 HD Webcam', 'Logitech', 'Accessories', 200),
    ('Logitech C930c HD Webcam', 'Logitech', 'Accessories', 200),
    ('Logitech Brio 4K Pro Webcam', 'Logitech', 'Accessories', 200),
    ('Logitech C505e HD Webcam', 'Logitech', 'Accessories', 200),
    ('Logitech Crayon Digital Pencil for iPad', 'Logitech', 'Accessories', 300),
    ('Logitech Pen Pro 2', 'Logitech', 'Accessories', 400),
    ('Logitech Pen Pro 3', 'Logitech', 'Accessories', 400),
    ('Logitech Digital Pen Pencil 4', 'Logitech', 'Accessories', 500),
    ('Logitech Pro Pen Digital Pencil 5', 'Logitech', 'Accessories', 500),
    ('Logitech Precision Pen Pro', 'Logitech', 'Accessories', 600),
    ('Logitech Smart Pen', 'Logitech', 'Accessories', 600),
    ('Logitech Intelligent Pen', 'Logitech', 'Accessories', 600),
    ('Logitech Signature Digital Pen', 'Logitech', 'Accessories', 700),
    ('Logitech Advanced Digital Pencil', 'Logitech', 'Accessories', 800),
    ('Logitech Pro Digital Pen', 'Logitech', 'Accessories', 800),
    ('Logitech Master Pen', 'Logitech', 'Accessories', 800),
    ('Logitech Supreme Digital Pen', 'Logitech', 'Accessories', 900),
    ('Logitech Elite Pen Pro', 'Logitech', 'Accessories', 900),
    ('Logitech Ultimate Digital Pen', 'Logitech', 'Accessories', 100),
    ('Logitech Professional Pen', 'Logitech', 'Accessories', 105),
    ('Logitech Executive Digital Pen', 'Logitech', 'Accessories', 110),
    ('Logitech Premium Pen', 'Logitech', 'Accessories', 115),
    ('Logitech Precision Digital Pencil', 'Logitech', 'Accessories', 120),
    ('Logitech Advanced Pen Pro', 'Logitech', 'Accessories', 120),
    ('Redmi Cam 1080p Webcam', 'Redmi', 'Webcams', 300),
    ('Redmi Vision Pro Webcam', 'Redmi', 'Webcams', 400),
    ('Redmi Eye 720p Webcam', 'Redmi', 'Webcams', 400),
    ('Redmi Stream Pro Webcam', 'Redmi', 'Webcams', 500),
    ('Redmi Cam Plus 4K Webcam', 'Redmi', 'Webcams', 500),
    ('Redmi Lens 1080p Webcam', 'Redmi', 'Webcams', 600),
    ('Redmi Sight HD Webcam', 'Redmi', 'Webcams', 600),
    ('Redmi Capture Pro Webcam', 'Redmi', 'Webcams', 600),
    ('Redmi View 720p Webcam', 'Redmi', 'Webcams', 700),
    ('Redmi Cam Max 1080p Webcam', 'Redmi', 'Webcams', 800),
    ('Redmi Visual 4K Webcam', 'Redmi', 'Webcams', 800),
    ('Redmi Stream 1080p Webcam', 'Redmi', 'Webcams', 800),
    ('Redmi Focus HD Webcam', 'Redmi', 'Webcams', 900),
    ('Redmi View Pro Webcam', 'Redmi', 'Webcams', 900),
    ('Redmi Lens Plus 720p Webcam', 'Redmi', 'Webcams', 100),
    ('Redmi Vision 4K Webcam', 'Redmi', 'Webcams', 105),
    ('Redmi Cam Pro 1080p Webcam', 'Redmi', 'Webcams', 110),
    ('Redmi Sight Plus HD Webcam', 'Redmi', 'Webcams', 115),
    ('Redmi Capture HD Webcam', 'Redmi', 'Webcams', 120),
    ('Redmi Visual Pro Webcam', 'Redmi', 'Webcams', 1250),
    ('Samsung Ultra Vision Webcam', 'Samsung', 'Webcams', 130),
    ('Samsung ProStream 4K Webcam', 'Samsung', 'Webcams', 135),
    ('Samsung Crystal Clear Webcam', 'Samsung', 'Webcams', 140),
    ('Samsung Wide Angle Webcam', 'Samsung', 'Webcams', 145),
    ('Samsung HD Live Streaming Webcam', 'Samsung', 'Webcams', 150),
    ('Samsung Cam360 Webcam', 'Samsung', 'Webcams', 155),
    ('Samsung ProShot Webcam', 'Samsung', 'Webcams', 160),
    ('Samsung Dynamic Focus Webcam', 'Samsung', 'Webcams', 165),
    ('Samsung SmartCapture Webcam', 'Samsung', 'Webcams', 170),
    ('Samsung PerfectView Webcam', 'Samsung', 'Webcams', 175),
    ('Samsung Cam 1080p Webcam', 'Samsung', 'Webcams', 300),
    ('Samsung Vision Pro Webcam', 'Samsung', 'Webcams', 400),
    ('Samsung Eye 720p Webcam', 'Samsung', 'Webcams', 400),
    ('Samsung Stream Pro Webcam', 'Samsung', 'Webcams', 500),
    ('Samsung Cam Plus 4K Webcam', 'Samsung', 'Webcams', 500),
    ('Samsung Lens 1080p Webcam', 'Samsung', 'Webcams', 600),
    ('Samsung Sight HD Webcam', 'Samsung', 'Webcams', 600),
    ('Samsung Capture Pro Webcam', 'Samsung', 'Webcams', 600),
    ('Samsung View 720p Webcam', 'Samsung', 'Webcams', 700),
    ('Samsung Cam Max 1080p Webcam', 'Samsung', 'Webcams', 800),
    ('Samsung Visual 4K Webcam', 'Samsung', 'Webcams', 800),
    ('Samsung Stream 1080p Webcam', 'Samsung', 'Webcams', 800),
    ('Samsung Focus HD Webcam', 'Samsung', 'Webcams', 900),
    ('Samsung View Pro Webcam', 'Samsung', 'Webcams', 900),
    ('Samsung Lens Plus 720p Webcam', 'Samsung', 'Webcams', 100),
    ('Samsung Vision 4K Webcam', 'Samsung', 'Webcams', 105),
    ('Samsung Cam Pro 1080p Webcam', 'Samsung', 'Webcams', 110),
    ('Samsung Sight Plus HD Webcam', 'Samsung', 'Webcams', 115),
    ('Samsung Capture HD Webcam', 'Samsung', 'Webcams', 120),
    ('Samsung Visual Pro Webcam', 'Samsung', 'Webcams', 1250),
    ('Realme BeatMaster Mic', 'Realme', 'Digital Microphones', 130),
    ('Realme HyperMic', 'Realme', 'Digital Microphones', 135),
    ('Realme Soundbox Mic', 'Realme', 'Digital Microphones', 140),
    ('Realme Sonic Mic', 'Realme', 'Digital Microphones', 145),
    ('Realme MasterSound Mic', 'Realme', 'Digital Microphones', 150),
    ('Realme PureAudio Mic', 'Realme', 'Digital Microphones', 155),
    ('Realme Vocalize Mic', 'Realme', 'Digital Microphones', 160),
    ('Realme TuneMax Mic', 'Realme', 'Digital Microphones', 165),
    ('Realme SoundScape Mic', 'Realme', 'Digital Microphones', 170),
    ('Realme Clarity Mic', 'Realme', 'Digital Microphones', 175),
    ('Realme Mic Pro', 'Realme', 'Digital Microphones', 300),
    ('Realme Mic Plus', 'Realme', 'Digital Microphones', 350),
    ('Realme Studio Mic', 'Realme', 'Digital Microphones', 400),
    ('Realme Sound Master Mic', 'Realme', 'Digital Microphones', 450),
    ('Realme Vocalist Mic', 'Realme', 'Digital Microphones', 500),
    ('Realme Voice Max Mic', 'Realme', 'Digital Microphones', 550),
    ('Realme Beatbox Mic', 'Realme', 'Digital Microphones', 600),
    ('Realme Echo Mic', 'Realme', 'Digital Microphones', 650),
    ('Realme Harmony Mic', 'Realme', 'Digital Microphones', 700),
    ('Realme Sound Forge Mic', 'Realme', 'Digital Microphones', 750),
    ('Realme Solo Mic', 'Realme', 'Digital Microphones', 800),
    ('Realme Dual Mic', 'Realme', 'Digital Microphones', 850),
    ('Realme Stereo Mic', 'Realme', 'Digital Microphones', 900),
    ('Realme Pro Sound Mic', 'Realme', 'Digital Microphones', 950),
    ('Realme Live Mic', 'Realme', 'Digital Microphones', 100),
    ('Realme Dynamic Mic', 'Realme', 'Digital Microphones', 105),
    ('Realme Soundwave Mic', 'Realme', 'Digital Microphones', 110),
    ('Realme Pixel Mic', 'Realme', 'Digital Microphones', 115),
    ('Realme Soundburst Mic', 'Realme', 'Digital Microphones', 120),
    ('Realme Ultra Mic', 'Realme', 'Digital Microphones', 1250),
    ('Logitech G Pro X Gaming Headset', 'Logitech', 'Headphones', 300),
    ('Logitech G733 Lightspeed Wireless Gaming Headset', 'Logitech', 'Headphones', 350),
    ('Logitech G935 Wireless DTS:X 7.1 Surround Sound LIGHTSYNC RGB PC Gaming Headset', 'Logitech', 'Headphones', 400),
    ('Logitech G Pro Gaming Headset', 'Logitech', 'Headphones', 450),
    ('Logitech G432 DTS:X 7.1 Surround Sound Wired PC Gaming Headset', 'Logitech', 'Headphones', 500),
    ('Logitech G335 Wired Gaming Headset', 'Logitech', 'Headphones', 550),
    ('Logitech G533 Wireless Gaming Headset', 'Logitech', 'Headphones', 600),
    ('Logitech G231 Prodigy Gaming Headset', 'Logitech', 'Headphones', 650),
    ('Logitech G432 DTS 7.1 Surround Sound Gaming Headset', 'Logitech', 'Headphones', 700),
    ('Logitech G935 Wireless DTS:X 7.1 Surround Sound Gaming Headset', 'Logitech', 'Headphones', 750),
    ('Logitech G533 Wireless DTS 7.1 Surround Sound Gaming Headset', 'Logitech', 'Headphones', 800),
    ('Logitech G433 7.1 Surround Sound Gaming Headset', 'Logitech', 'Headphones', 850),
    ('Logitech G PRO X Gaming Headset (2nd Generation)', 'Logitech', 'Headphones', 900),
    ('Logitech G335 Wired Gaming Headset (2nd Generation)', 'Logitech', 'Headphones', 950),
    ('Logitech G433 7.1 Wired Gaming Headset', 'Logitech', 'Headphones', 100),
    ('Logitech G533 Wireless Gaming Headset (2nd Generation)', 'Logitech', 'Headphones', 105),
    ('Logitech G PRO X LIGHTSPEED Wireless Gaming Headset', 'Logitech', 'Headphones', 110),
    ('Logitech G332 Stereo Gaming Headset', 'Logitech', 'Headphones', 115),
    ('Logitech G433 DTS 7.1 Wired Gaming Headset', 'Logitech', 'Headphones', 120),
    ('Logitech G935 Wireless 7.1 Surround Sound Gaming Headset', 'Logitech', 'Headphones', 1250),
    ('Logitech G Pro X Gaming Headset (3rd Generation)', 'Logitech', 'Headphones', 130),
    ('Logitech G533 Prodigy Wireless Gaming Headset', 'Logitech', 'Headphones', 135),
    ('Logitech G733 Lightspeed Wireless Gaming Headset (2nd Generation)', 'Logitech', 'Headphones', 140),
    ('Logitech G432 7.1 Surround Sound Gaming Headset', 'Logitech', 'Headphones', 145),
    ('Logitech G231 Gaming Headset', 'Logitech', 'Headphones', 150),
    ('Logitech G PRO X Wireless Gaming Headset', 'Logitech', 'Headphones', 155),
    ('Logitech G332 Wired Gaming Headset', 'Logitech', 'Headphones', 160),
    ('Logitech G432 DTS:X 7.1 Surround Sound Wired Gaming Headset', 'Logitech', 'Headphones', 165),
    ('Logitech G733 LIGHTSPEED Wireless Gaming Headset (3rd Generation)', 'Logitech', 'Headphones', 170),
    ('Logitech G231 Prodigy Stereo Gaming Headset', 'Logitech', 'Headphones', 175),
    ('Logitech G PRO Gaming Headset (2nd Generation)', 'Logitech', 'Headphones', 180)
]

# Connect to MySQL database
conn = pymysql.connect(host='localhost',
                       user='root',
                       password='root',
                       database='warehouse',
                       charset='utf8mb4',
                       cursorclass=pymysql.cursors.DictCursor)

try:
    with conn.cursor() as cursor:
        # Delete existing data from the table
        cursor.execute("DELETE FROM products")

        warehouse = "Warehouse"
        counter = 1  # Initialize a counter

        for i in products:
            product_id = i[0][:3].upper() + i[1][:2].upper() + i[2][:2].upper() + str(counter)
            
            try:
                cursor.execute("INSERT INTO products VALUES (%s, %s, %s, %s, %s, %s)",
                            (product_id, i[0], i[1], i[2], warehouse, i[3]))
                counter += 1  # Increment counter after successful insert
            except pymysql.err.IntegrityError as e:
                print(f"Error inserting {product_id}: {e}")

    # Commit changes
    conn.commit()
    print("Data inserted successfully.")
finally:
    conn.close()
    # Close connectionconn.close()